// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_type::Ability;
use super::caster_progression_type::CasterProgression;
use super::dnd_5_e_class_type::Dnd5EClass;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_class`.
///
/// Obtain a handle from the [`Dnd5EClassTableAccess::dnd_5_e_class`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_class()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_class().on_insert(...)`.
pub struct Dnd5EClassTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EClass>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_class`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EClassTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EClassTableHandle`], which mediates access to the table `dnd_5_e_class`.
    fn dnd_5_e_class(&self) -> Dnd5EClassTableHandle<'_>;
}

impl Dnd5EClassTableAccess for super::RemoteTables {
    fn dnd_5_e_class(&self) -> Dnd5EClassTableHandle<'_> {
        Dnd5EClassTableHandle {
            imp: self.imp.get_table::<Dnd5EClass>("dnd_5_e_class"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EClassInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EClassDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EClassTableHandle<'ctx> {
    type Row = Dnd5EClass;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EClass> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EClassInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassInsertCallbackId {
        Dnd5EClassInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EClassInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EClassDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassDeleteCallbackId {
        Dnd5EClassDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EClassDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EClassUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EClassTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EClassUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassUpdateCallbackId {
        Dnd5EClassUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EClassUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_class`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EClassIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_class().id().find(...)`.
pub struct Dnd5EClassIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EClass, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EClassTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_class`.
    pub fn id(&self) -> Dnd5EClassIdUnique<'ctx> {
        Dnd5EClassIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EClassIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EClass> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EClass>("dnd_5_e_class");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EClass>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EClass>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EClass`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_classQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EClass`.
    fn dnd_5_e_class(&self) -> __sdk::__query_builder::Table<Dnd5EClass>;
}

impl dnd_5_e_classQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_class(&self) -> __sdk::__query_builder::Table<Dnd5EClass> {
        __sdk::__query_builder::Table::new("dnd_5_e_class")
    }
}
