// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_size_type::CreatureSize;
use super::creature_type_type::CreatureType;
use super::dnd_5_e_monster_type::Dnd5EMonster;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_monster`.
///
/// Obtain a handle from the [`Dnd5EMonsterTableAccess::dnd_5_e_monster`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_monster()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_monster().on_insert(...)`.
pub struct Dnd5EMonsterTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EMonster>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_monster`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EMonsterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EMonsterTableHandle`], which mediates access to the table `dnd_5_e_monster`.
    fn dnd_5_e_monster(&self) -> Dnd5EMonsterTableHandle<'_>;
}

impl Dnd5EMonsterTableAccess for super::RemoteTables {
    fn dnd_5_e_monster(&self) -> Dnd5EMonsterTableHandle<'_> {
        Dnd5EMonsterTableHandle {
            imp: self.imp.get_table::<Dnd5EMonster>("dnd_5_e_monster"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EMonsterInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EMonsterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EMonsterTableHandle<'ctx> {
    type Row = Dnd5EMonster;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EMonster> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EMonsterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EMonsterInsertCallbackId {
        Dnd5EMonsterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EMonsterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EMonsterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EMonsterDeleteCallbackId {
        Dnd5EMonsterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EMonsterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EMonsterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EMonsterTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EMonsterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EMonsterUpdateCallbackId {
        Dnd5EMonsterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EMonsterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_monster`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EMonsterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_monster().id().find(...)`.
pub struct Dnd5EMonsterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EMonster, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EMonsterTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_monster`.
    pub fn id(&self) -> Dnd5EMonsterIdUnique<'ctx> {
        Dnd5EMonsterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EMonsterIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EMonster> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EMonster>("dnd_5_e_monster");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EMonster>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EMonster>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EMonster`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_monsterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EMonster`.
    fn dnd_5_e_monster(&self) -> __sdk::__query_builder::Table<Dnd5EMonster>;
}

impl dnd_5_e_monsterQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_monster(&self) -> __sdk::__query_builder::Table<Dnd5EMonster> {
        __sdk::__query_builder::Table::new("dnd_5_e_monster")
    }
}
