// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_feat_type::Dnd5EFeat;
use super::feat_category_type::FeatCategory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_feat`.
///
/// Obtain a handle from the [`Dnd5EFeatTableAccess::dnd_5_e_feat`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_feat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_feat().on_insert(...)`.
pub struct Dnd5EFeatTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EFeat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_feat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EFeatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EFeatTableHandle`], which mediates access to the table `dnd_5_e_feat`.
    fn dnd_5_e_feat(&self) -> Dnd5EFeatTableHandle<'_>;
}

impl Dnd5EFeatTableAccess for super::RemoteTables {
    fn dnd_5_e_feat(&self) -> Dnd5EFeatTableHandle<'_> {
        Dnd5EFeatTableHandle {
            imp: self.imp.get_table::<Dnd5EFeat>("dnd_5_e_feat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EFeatInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EFeatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EFeatTableHandle<'ctx> {
    type Row = Dnd5EFeat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EFeat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EFeatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EFeatInsertCallbackId {
        Dnd5EFeatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EFeatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EFeatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EFeatDeleteCallbackId {
        Dnd5EFeatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EFeatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EFeatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EFeatTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EFeatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EFeatUpdateCallbackId {
        Dnd5EFeatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EFeatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_feat`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EFeatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_feat().id().find(...)`.
pub struct Dnd5EFeatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EFeat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EFeatTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_feat`.
    pub fn id(&self) -> Dnd5EFeatIdUnique<'ctx> {
        Dnd5EFeatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EFeatIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EFeat> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EFeat>("dnd_5_e_feat");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EFeat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EFeat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EFeat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_featQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EFeat`.
    fn dnd_5_e_feat(&self) -> __sdk::__query_builder::Table<Dnd5EFeat>;
}

impl dnd_5_e_featQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_feat(&self) -> __sdk::__query_builder::Table<Dnd5EFeat> {
        __sdk::__query_builder::Table::new("dnd_5_e_feat")
    }
}
