// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_type::Ability;
use super::spell_school_type::SpellSchool;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ESpell {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub level: u8,
    pub school: SpellSchool,
    pub ritual: bool,
    pub concentration: bool,
    pub description: String,
    pub saving_throw: Option<Ability>,
}

impl __sdk::InModule for Dnd5ESpell {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ESpell`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ESpellCols {
    pub id: __sdk::__query_builder::Col<Dnd5ESpell, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ESpell, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ESpell, String>,
    pub level: __sdk::__query_builder::Col<Dnd5ESpell, u8>,
    pub school: __sdk::__query_builder::Col<Dnd5ESpell, SpellSchool>,
    pub ritual: __sdk::__query_builder::Col<Dnd5ESpell, bool>,
    pub concentration: __sdk::__query_builder::Col<Dnd5ESpell, bool>,
    pub description: __sdk::__query_builder::Col<Dnd5ESpell, String>,
    pub saving_throw: __sdk::__query_builder::Col<Dnd5ESpell, Option<Ability>>,
}

impl __sdk::__query_builder::HasCols for Dnd5ESpell {
    type Cols = Dnd5ESpellCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ESpellCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            school: __sdk::__query_builder::Col::new(table_name, "school"),
            ritual: __sdk::__query_builder::Col::new(table_name, "ritual"),
            concentration: __sdk::__query_builder::Col::new(table_name, "concentration"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            saving_throw: __sdk::__query_builder::Col::new(table_name, "saving_throw"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ESpell`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ESpellIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ESpell, u64>,
    pub saving_throw: __sdk::__query_builder::IxCol<Dnd5ESpell, Option<Ability>>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ESpell {
    type IxCols = Dnd5ESpellIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ESpellIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            saving_throw: __sdk::__query_builder::IxCol::new(table_name, "saving_throw"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ESpell {}
