// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ESubclassFeature {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub class_name: String,
    pub class_source: String,
    pub subclass_short_name: String,
    pub subclass_source: String,
    pub level: u8,
    pub description: String,
}

impl __sdk::InModule for Dnd5ESubclassFeature {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ESubclassFeature`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ESubclassFeatureCols {
    pub id: __sdk::__query_builder::Col<Dnd5ESubclassFeature, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub class_name: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub class_source: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub subclass_short_name: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub subclass_source: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
    pub level: __sdk::__query_builder::Col<Dnd5ESubclassFeature, u8>,
    pub description: __sdk::__query_builder::Col<Dnd5ESubclassFeature, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ESubclassFeature {
    type Cols = Dnd5ESubclassFeatureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ESubclassFeatureCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            class_name: __sdk::__query_builder::Col::new(table_name, "class_name"),
            class_source: __sdk::__query_builder::Col::new(table_name, "class_source"),
            subclass_short_name: __sdk::__query_builder::Col::new(
                table_name,
                "subclass_short_name",
            ),
            subclass_source: __sdk::__query_builder::Col::new(table_name, "subclass_source"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ESubclassFeature`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ESubclassFeatureIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ESubclassFeature, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ESubclassFeature {
    type IxCols = Dnd5ESubclassFeatureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ESubclassFeatureIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ESubclassFeature {}
