// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit f3109bbaa05d2de4d801394058adca36903d4259).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ability_bonus_type;
pub mod ability_choice_type;
pub mod ability_grant_type;
pub mod ability_type;
pub mod creature_size_type;
pub mod creature_type_type;
pub mod dnd_5_e_background_table;
pub mod dnd_5_e_background_type;
pub mod dnd_5_e_condition_table;
pub mod dnd_5_e_condition_type;
pub mod dnd_5_e_feat_table;
pub mod dnd_5_e_feat_type;
pub mod dnd_5_e_item_table;
pub mod dnd_5_e_item_type;
pub mod dnd_5_e_monster_table;
pub mod dnd_5_e_monster_type;
pub mod dnd_5_e_race_table;
pub mod dnd_5_e_race_type;
pub mod dnd_5_e_spell_table;
pub mod dnd_5_e_spell_type;
pub mod feat_category_type;
pub mod item_rarity_type;
pub mod item_type_type;
pub mod language_choice_type;
pub mod language_grant_type;
pub mod language_type;
pub mod message_table;
pub mod message_type;
pub mod seed_dnd_5_e_background_reducer;
pub mod seed_dnd_5_e_condition_reducer;
pub mod seed_dnd_5_e_feat_reducer;
pub mod seed_dnd_5_e_item_reducer;
pub mod seed_dnd_5_e_monster_reducer;
pub mod seed_dnd_5_e_race_reducer;
pub mod seed_dnd_5_e_spell_reducer;
pub mod send_message_reducer;
pub mod set_name_reducer;
pub mod skill_choice_type;
pub mod skill_grant_type;
pub mod skill_type;
pub mod speed_type;
pub mod spell_school_type;
pub mod string_choice_type;
pub mod tool_grant_type;
pub mod user_table;
pub mod user_type;

pub use ability_bonus_type::AbilityBonus;
pub use ability_choice_type::AbilityChoice;
pub use ability_grant_type::AbilityGrant;
pub use ability_type::Ability;
pub use creature_size_type::CreatureSize;
pub use creature_type_type::CreatureType;
pub use dnd_5_e_background_table::*;
pub use dnd_5_e_background_type::Dnd5EBackground;
pub use dnd_5_e_condition_table::*;
pub use dnd_5_e_condition_type::Dnd5ECondition;
pub use dnd_5_e_feat_table::*;
pub use dnd_5_e_feat_type::Dnd5EFeat;
pub use dnd_5_e_item_table::*;
pub use dnd_5_e_item_type::Dnd5EItem;
pub use dnd_5_e_monster_table::*;
pub use dnd_5_e_monster_type::Dnd5EMonster;
pub use dnd_5_e_race_table::*;
pub use dnd_5_e_race_type::Dnd5ERace;
pub use dnd_5_e_spell_table::*;
pub use dnd_5_e_spell_type::Dnd5ESpell;
pub use feat_category_type::FeatCategory;
pub use item_rarity_type::ItemRarity;
pub use item_type_type::ItemType;
pub use language_choice_type::LanguageChoice;
pub use language_grant_type::LanguageGrant;
pub use language_type::Language;
pub use message_table::*;
pub use message_type::Message;
pub use seed_dnd_5_e_background_reducer::seed_dnd_5_e_background;
pub use seed_dnd_5_e_condition_reducer::seed_dnd_5_e_condition;
pub use seed_dnd_5_e_feat_reducer::seed_dnd_5_e_feat;
pub use seed_dnd_5_e_item_reducer::seed_dnd_5_e_item;
pub use seed_dnd_5_e_monster_reducer::seed_dnd_5_e_monster;
pub use seed_dnd_5_e_race_reducer::seed_dnd_5_e_race;
pub use seed_dnd_5_e_spell_reducer::seed_dnd_5_e_spell;
pub use send_message_reducer::send_message;
pub use set_name_reducer::set_name;
pub use skill_choice_type::SkillChoice;
pub use skill_grant_type::SkillGrant;
pub use skill_type::Skill;
pub use speed_type::Speed;
pub use spell_school_type::SpellSchool;
pub use string_choice_type::StringChoice;
pub use tool_grant_type::ToolGrant;
pub use user_table::*;
pub use user_type::User;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    SeedDnd5EBackground {
        name: String,
        source: String,
        skill_proficiencies: Vec<SkillGrant>,
        tool_proficiencies: Vec<ToolGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    },
    SeedDnd5ECondition {
        name: String,
        source: String,
        description: String,
    },
    SeedDnd5EFeat {
        name: String,
        source: String,
        category: Option<FeatCategory>,
        prerequisite: Option<String>,
        description: String,
    },
    SeedDnd5EItem {
        name: String,
        source: String,
        item_type: ItemType,
        rarity: ItemRarity,
        weight: Option<f32>,
        value_cp: Option<u32>,
        wondrous: bool,
        attunement: Option<String>,
        description: String,
    },
    SeedDnd5EMonster {
        name: String,
        source: String,
        size: CreatureSize,
        creature_type: CreatureType,
        cr: String,
        ac: u8,
        hp_average: u16,
        hp_formula: String,
        speed_walk: u16,
        speed_fly: u16,
        speed_swim: u16,
        str_score: u8,
        dex_score: u8,
        con_score: u8,
        int_score: u8,
        wis_score: u8,
        cha_score: u8,
        description: String,
    },
    SeedDnd5ERace {
        name: String,
        source: String,
        size: CreatureSize,
        speed: Speed,
        ability_bonuses: Vec<AbilityGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    },
    SeedDnd5ESpell {
        name: String,
        source: String,
        level: u8,
        school: SpellSchool,
        ritual: bool,
        concentration: bool,
        description: String,
        saving_throw: Option<Ability>,
    },
    SendMessage {
        text: String,
    },
    SetName {
        name: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::SeedDnd5EBackground { .. } => "seed_dnd_5_e_background",
            Reducer::SeedDnd5ECondition { .. } => "seed_dnd_5_e_condition",
            Reducer::SeedDnd5EFeat { .. } => "seed_dnd_5_e_feat",
            Reducer::SeedDnd5EItem { .. } => "seed_dnd_5_e_item",
            Reducer::SeedDnd5EMonster { .. } => "seed_dnd_5_e_monster",
            Reducer::SeedDnd5ERace { .. } => "seed_dnd_5_e_race",
            Reducer::SeedDnd5ESpell { .. } => "seed_dnd_5_e_spell",
            Reducer::SendMessage { .. } => "send_message",
            Reducer::SetName { .. } => "set_name",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::SeedDnd5EBackground {
                name,
                source,
                skill_proficiencies,
                tool_proficiencies,
                language_proficiencies,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_background_reducer::SeedDnd5EBackgroundArgs {
                name: name.clone(),
                source: source.clone(),
                skill_proficiencies: skill_proficiencies.clone(),
                tool_proficiencies: tool_proficiencies.clone(),
                language_proficiencies: language_proficiencies.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ECondition {
                name,
                source,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_condition_reducer::SeedDnd5EConditionArgs {
                name: name.clone(),
                source: source.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EFeat {
                name,
                source,
                category,
                prerequisite,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_feat_reducer::SeedDnd5EFeatArgs {
                name: name.clone(),
                source: source.clone(),
                category: category.clone(),
                prerequisite: prerequisite.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EItem {
                name,
                source,
                item_type,
                rarity,
                weight,
                value_cp,
                wondrous,
                attunement,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_item_reducer::SeedDnd5EItemArgs {
                name: name.clone(),
                source: source.clone(),
                item_type: item_type.clone(),
                rarity: rarity.clone(),
                weight: weight.clone(),
                value_cp: value_cp.clone(),
                wondrous: wondrous.clone(),
                attunement: attunement.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EMonster {
                name,
                source,
                size,
                creature_type,
                cr,
                ac,
                hp_average,
                hp_formula,
                speed_walk,
                speed_fly,
                speed_swim,
                str_score,
                dex_score,
                con_score,
                int_score,
                wis_score,
                cha_score,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_monster_reducer::SeedDnd5EMonsterArgs {
                name: name.clone(),
                source: source.clone(),
                size: size.clone(),
                creature_type: creature_type.clone(),
                cr: cr.clone(),
                ac: ac.clone(),
                hp_average: hp_average.clone(),
                hp_formula: hp_formula.clone(),
                speed_walk: speed_walk.clone(),
                speed_fly: speed_fly.clone(),
                speed_swim: speed_swim.clone(),
                str_score: str_score.clone(),
                dex_score: dex_score.clone(),
                con_score: con_score.clone(),
                int_score: int_score.clone(),
                wis_score: wis_score.clone(),
                cha_score: cha_score.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ERace {
                name,
                source,
                size,
                speed,
                ability_bonuses,
                language_proficiencies,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_race_reducer::SeedDnd5ERaceArgs {
                name: name.clone(),
                source: source.clone(),
                size: size.clone(),
                speed: speed.clone(),
                ability_bonuses: ability_bonuses.clone(),
                language_proficiencies: language_proficiencies.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ESpell {
                name,
                source,
                level,
                school,
                ritual,
                concentration,
                description,
                saving_throw,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_spell_reducer::SeedDnd5ESpellArgs {
                name: name.clone(),
                source: source.clone(),
                level: level.clone(),
                school: school.clone(),
                ritual: ritual.clone(),
                concentration: concentration.clone(),
                description: description.clone(),
                saving_throw: saving_throw.clone(),
            }),
            Reducer::SendMessage { text } => {
                __sats::bsatn::to_vec(&send_message_reducer::SendMessageArgs { text: text.clone() })
            }
            Reducer::SetName { name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { name: name.clone() })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    dnd_5_e_background: __sdk::TableUpdate<Dnd5EBackground>,
    dnd_5_e_condition: __sdk::TableUpdate<Dnd5ECondition>,
    dnd_5_e_feat: __sdk::TableUpdate<Dnd5EFeat>,
    dnd_5_e_item: __sdk::TableUpdate<Dnd5EItem>,
    dnd_5_e_monster: __sdk::TableUpdate<Dnd5EMonster>,
    dnd_5_e_race: __sdk::TableUpdate<Dnd5ERace>,
    dnd_5_e_spell: __sdk::TableUpdate<Dnd5ESpell>,
    message: __sdk::TableUpdate<Message>,
    user: __sdk::TableUpdate<User>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(dnd_5_e_background_table::parse_table_update(table_update)?),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(dnd_5_e_condition_table::parse_table_update(table_update)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(dnd_5_e_feat_table::parse_table_update(table_update)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(dnd_5_e_item_table::parse_table_update(table_update)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(dnd_5_e_monster_table::parse_table_update(table_update)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(dnd_5_e_race_table::parse_table_update(table_update)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(dnd_5_e_spell_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.dnd_5_e_background = cache
            .apply_diff_to_table::<Dnd5EBackground>("dnd_5_e_background", &self.dnd_5_e_background)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_condition = cache
            .apply_diff_to_table::<Dnd5ECondition>("dnd_5_e_condition", &self.dnd_5_e_condition)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_feat = cache
            .apply_diff_to_table::<Dnd5EFeat>("dnd_5_e_feat", &self.dnd_5_e_feat)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_item = cache
            .apply_diff_to_table::<Dnd5EItem>("dnd_5_e_item", &self.dnd_5_e_item)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_monster = cache
            .apply_diff_to_table::<Dnd5EMonster>("dnd_5_e_monster", &self.dnd_5_e_monster)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_race = cache
            .apply_diff_to_table::<Dnd5ERace>("dnd_5_e_race", &self.dnd_5_e_race)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_spell = cache
            .apply_diff_to_table::<Dnd5ESpell>("dnd_5_e_spell", &self.dnd_5_e_spell)
            .with_updates_by_pk(|row| &row.id);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    dnd_5_e_background: __sdk::TableAppliedDiff<'r, Dnd5EBackground>,
    dnd_5_e_condition: __sdk::TableAppliedDiff<'r, Dnd5ECondition>,
    dnd_5_e_feat: __sdk::TableAppliedDiff<'r, Dnd5EFeat>,
    dnd_5_e_item: __sdk::TableAppliedDiff<'r, Dnd5EItem>,
    dnd_5_e_monster: __sdk::TableAppliedDiff<'r, Dnd5EMonster>,
    dnd_5_e_race: __sdk::TableAppliedDiff<'r, Dnd5ERace>,
    dnd_5_e_spell: __sdk::TableAppliedDiff<'r, Dnd5ESpell>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    user: __sdk::TableAppliedDiff<'r, User>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Dnd5EBackground>(
            "dnd_5_e_background",
            &self.dnd_5_e_background,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ECondition>(
            "dnd_5_e_condition",
            &self.dnd_5_e_condition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EFeat>(
            "dnd_5_e_feat",
            &self.dnd_5_e_feat,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EItem>(
            "dnd_5_e_item",
            &self.dnd_5_e_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EMonster>(
            "dnd_5_e_monster",
            &self.dnd_5_e_monster,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ERace>(
            "dnd_5_e_race",
            &self.dnd_5_e_race,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESpell>(
            "dnd_5_e_spell",
            &self.dnd_5_e_spell,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        dnd_5_e_background_table::register_table(client_cache);
        dnd_5_e_condition_table::register_table(client_cache);
        dnd_5_e_feat_table::register_table(client_cache);
        dnd_5_e_item_table::register_table(client_cache);
        dnd_5_e_monster_table::register_table(client_cache);
        dnd_5_e_race_table::register_table(client_cache);
        dnd_5_e_spell_table::register_table(client_cache);
        message_table::register_table(client_cache);
        user_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "dnd_5_e_background",
        "dnd_5_e_condition",
        "dnd_5_e_feat",
        "dnd_5_e_item",
        "dnd_5_e_monster",
        "dnd_5_e_race",
        "dnd_5_e_spell",
        "message",
        "user",
    ];
}
