// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ESubclassFeatureArgs {
    pub name: String,
    pub source: String,
    pub class_name: String,
    pub class_source: String,
    pub subclass_short_name: String,
    pub subclass_source: String,
    pub level: u8,
    pub description: String,
}

impl From<SeedDnd5ESubclassFeatureArgs> for super::Reducer {
    fn from(args: SeedDnd5ESubclassFeatureArgs) -> Self {
        Self::SeedDnd5ESubclassFeature {
            name: args.name,
            source: args.source,
            class_name: args.class_name,
            class_source: args.class_source,
            subclass_short_name: args.subclass_short_name,
            subclass_source: args.subclass_source,
            level: args.level,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5ESubclassFeatureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_subclass_feature`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_subclass_feature {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_subclass_feature` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_subclass_feature:seed_dnd_5_e_subclass_feature_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_subclass_feature(
        &self,
        name: String,
        source: String,
        class_name: String,
        class_source: String,
        subclass_short_name: String,
        subclass_source: String,
        level: u8,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_subclass_feature_then(
            name,
            source,
            class_name,
            class_source,
            subclass_short_name,
            subclass_source,
            level,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_subclass_feature` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_subclass_feature_then(
        &self,
        name: String,
        source: String,
        class_name: String,
        class_source: String,
        subclass_short_name: String,
        subclass_source: String,
        level: u8,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_subclass_feature for super::RemoteReducers {
    fn seed_dnd_5_e_subclass_feature_then(
        &self,
        name: String,
        source: String,
        class_name: String,
        class_source: String,
        subclass_short_name: String,
        subclass_source: String,
        level: u8,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ESubclassFeatureArgs {
                name,
                source,
                class_name,
                class_source,
                subclass_short_name,
                subclass_source,
                level,
                description,
            },
            callback,
        )
    }
}
