// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::optional_feature_prereq_type::OptionalFeaturePrereq;
use super::optional_feature_type_type::OptionalFeatureType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EOptionalFeatureArgs {
    pub name: String,
    pub source: String,
    pub feature_types: Vec<OptionalFeatureType>,
    pub prerequisite: Option<OptionalFeaturePrereq>,
    pub description: String,
}

impl From<SeedDnd5EOptionalFeatureArgs> for super::Reducer {
    fn from(args: SeedDnd5EOptionalFeatureArgs) -> Self {
        Self::SeedDnd5EOptionalFeature {
            name: args.name,
            source: args.source,
            feature_types: args.feature_types,
            prerequisite: args.prerequisite,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EOptionalFeatureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_optional_feature`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_optional_feature {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_optional_feature` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_optional_feature:seed_dnd_5_e_optional_feature_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_optional_feature(
        &self,
        name: String,
        source: String,
        feature_types: Vec<OptionalFeatureType>,
        prerequisite: Option<OptionalFeaturePrereq>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_optional_feature_then(
            name,
            source,
            feature_types,
            prerequisite,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_optional_feature` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_optional_feature_then(
        &self,
        name: String,
        source: String,
        feature_types: Vec<OptionalFeatureType>,
        prerequisite: Option<OptionalFeaturePrereq>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_optional_feature for super::RemoteReducers {
    fn seed_dnd_5_e_optional_feature_then(
        &self,
        name: String,
        source: String,
        feature_types: Vec<OptionalFeatureType>,
        prerequisite: Option<OptionalFeaturePrereq>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EOptionalFeatureArgs {
                name,
                source,
                feature_types,
                prerequisite,
                description,
            },
            callback,
        )
    }
}
