// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EConditionArgs {
    pub name: String,
    pub source: String,
    pub description: String,
}

impl From<SeedDnd5EConditionArgs> for super::Reducer {
    fn from(args: SeedDnd5EConditionArgs) -> Self {
        Self::SeedDnd5ECondition {
            name: args.name,
            source: args.source,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EConditionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_condition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_condition {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_condition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_condition:seed_dnd_5_e_condition_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_condition(
        &self,
        name: String,
        source: String,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_condition_then(name, source, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_condition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_condition_then(
        &self,
        name: String,
        source: String,
        description: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_condition for super::RemoteReducers {
    fn seed_dnd_5_e_condition_then(
        &self,
        name: String,
        source: String,
        description: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EConditionArgs {
                name,
                source,
                description,
            },
            callback,
        )
    }
}
