// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::creature_size_type::CreatureSize;
use super::creature_type_type::CreatureType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EMonsterArgs {
    pub name: String,
    pub source: String,
    pub size: CreatureSize,
    pub creature_type: CreatureType,
    pub cr: String,
    pub ac: u8,
    pub hp_average: u16,
    pub hp_formula: String,
    pub speed_walk: u16,
    pub speed_fly: u16,
    pub speed_swim: u16,
    pub str_score: u8,
    pub dex_score: u8,
    pub con_score: u8,
    pub int_score: u8,
    pub wis_score: u8,
    pub cha_score: u8,
    pub description: String,
}

impl From<SeedDnd5EMonsterArgs> for super::Reducer {
    fn from(args: SeedDnd5EMonsterArgs) -> Self {
        Self::SeedDnd5EMonster {
            name: args.name,
            source: args.source,
            size: args.size,
            creature_type: args.creature_type,
            cr: args.cr,
            ac: args.ac,
            hp_average: args.hp_average,
            hp_formula: args.hp_formula,
            speed_walk: args.speed_walk,
            speed_fly: args.speed_fly,
            speed_swim: args.speed_swim,
            str_score: args.str_score,
            dex_score: args.dex_score,
            con_score: args.con_score,
            int_score: args.int_score,
            wis_score: args.wis_score,
            cha_score: args.cha_score,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EMonsterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_monster`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_monster {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_monster` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_monster:seed_dnd_5_e_monster_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_monster(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        creature_type: CreatureType,
        cr: String,
        ac: u8,
        hp_average: u16,
        hp_formula: String,
        speed_walk: u16,
        speed_fly: u16,
        speed_swim: u16,
        str_score: u8,
        dex_score: u8,
        con_score: u8,
        int_score: u8,
        wis_score: u8,
        cha_score: u8,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_monster_then(
            name,
            source,
            size,
            creature_type,
            cr,
            ac,
            hp_average,
            hp_formula,
            speed_walk,
            speed_fly,
            speed_swim,
            str_score,
            dex_score,
            con_score,
            int_score,
            wis_score,
            cha_score,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_monster` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_monster_then(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        creature_type: CreatureType,
        cr: String,
        ac: u8,
        hp_average: u16,
        hp_formula: String,
        speed_walk: u16,
        speed_fly: u16,
        speed_swim: u16,
        str_score: u8,
        dex_score: u8,
        con_score: u8,
        int_score: u8,
        wis_score: u8,
        cha_score: u8,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_monster for super::RemoteReducers {
    fn seed_dnd_5_e_monster_then(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        creature_type: CreatureType,
        cr: String,
        ac: u8,
        hp_average: u16,
        hp_formula: String,
        speed_walk: u16,
        speed_fly: u16,
        speed_swim: u16,
        str_score: u8,
        dex_score: u8,
        con_score: u8,
        int_score: u8,
        wis_score: u8,
        cha_score: u8,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EMonsterArgs {
                name,
                source,
                size,
                creature_type,
                cr,
                ac,
                hp_average,
                hp_formula,
                speed_walk,
                speed_fly,
                speed_swim,
                str_score,
                dex_score,
                con_score,
                int_score,
                wis_score,
                cha_score,
                description,
            },
            callback,
        )
    }
}
