// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::language_grant_type::LanguageGrant;
use super::skill_grant_type::SkillGrant;
use super::tool_grant_type::ToolGrant;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EBackgroundArgs {
    pub name: String,
    pub source: String,
    pub skill_proficiencies: Vec<SkillGrant>,
    pub tool_proficiencies: Vec<ToolGrant>,
    pub language_proficiencies: Vec<LanguageGrant>,
    pub description: String,
}

impl From<SeedDnd5EBackgroundArgs> for super::Reducer {
    fn from(args: SeedDnd5EBackgroundArgs) -> Self {
        Self::SeedDnd5EBackground {
            name: args.name,
            source: args.source,
            skill_proficiencies: args.skill_proficiencies,
            tool_proficiencies: args.tool_proficiencies,
            language_proficiencies: args.language_proficiencies,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EBackgroundArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_background`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_background {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_background` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_background:seed_dnd_5_e_background_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_background(
        &self,
        name: String,
        source: String,
        skill_proficiencies: Vec<SkillGrant>,
        tool_proficiencies: Vec<ToolGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_background_then(
            name,
            source,
            skill_proficiencies,
            tool_proficiencies,
            language_proficiencies,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_background` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_background_then(
        &self,
        name: String,
        source: String,
        skill_proficiencies: Vec<SkillGrant>,
        tool_proficiencies: Vec<ToolGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_background for super::RemoteReducers {
    fn seed_dnd_5_e_background_then(
        &self,
        name: String,
        source: String,
        skill_proficiencies: Vec<SkillGrant>,
        tool_proficiencies: Vec<ToolGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EBackgroundArgs {
                name,
                source,
                skill_proficiencies,
                tool_proficiencies,
                language_proficiencies,
                description,
            },
            callback,
        )
    }
}
