// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_type::Ability;
use super::caster_progression_type::CasterProgression;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ESubclass {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub short_name: String,
    pub source: String,
    pub class_name: String,
    pub class_source: String,
    pub edition: Option<String>,
    pub spellcasting_ability: Option<Ability>,
    pub caster_progression: Option<CasterProgression>,
    pub cantrip_progression: Vec<u8>,
    pub subclass_features: Vec<String>,
}

impl __sdk::InModule for Dnd5ESubclass {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ESubclass`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ESubclassCols {
    pub id: __sdk::__query_builder::Col<Dnd5ESubclass, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub name: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub short_name: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub class_name: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub class_source: __sdk::__query_builder::Col<Dnd5ESubclass, String>,
    pub edition: __sdk::__query_builder::Col<Dnd5ESubclass, Option<String>>,
    pub spellcasting_ability: __sdk::__query_builder::Col<Dnd5ESubclass, Option<Ability>>,
    pub caster_progression: __sdk::__query_builder::Col<Dnd5ESubclass, Option<CasterProgression>>,
    pub cantrip_progression: __sdk::__query_builder::Col<Dnd5ESubclass, Vec<u8>>,
    pub subclass_features: __sdk::__query_builder::Col<Dnd5ESubclass, Vec<String>>,
}

impl __sdk::__query_builder::HasCols for Dnd5ESubclass {
    type Cols = Dnd5ESubclassCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ESubclassCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            short_name: __sdk::__query_builder::Col::new(table_name, "short_name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            class_name: __sdk::__query_builder::Col::new(table_name, "class_name"),
            class_source: __sdk::__query_builder::Col::new(table_name, "class_source"),
            edition: __sdk::__query_builder::Col::new(table_name, "edition"),
            spellcasting_ability: __sdk::__query_builder::Col::new(
                table_name,
                "spellcasting_ability",
            ),
            caster_progression: __sdk::__query_builder::Col::new(table_name, "caster_progression"),
            cantrip_progression: __sdk::__query_builder::Col::new(
                table_name,
                "cantrip_progression",
            ),
            subclass_features: __sdk::__query_builder::Col::new(table_name, "subclass_features"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ESubclass`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ESubclassIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ESubclass, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5ESubclass, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ESubclass {
    type IxCols = Dnd5ESubclassIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ESubclassIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ESubclass {}
