// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_vehicle_type::Dnd5EVehicle;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_vehicle`.
///
/// Obtain a handle from the [`Dnd5EVehicleTableAccess::dnd_5_e_vehicle`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_vehicle()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_vehicle().on_insert(...)`.
pub struct Dnd5EVehicleTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EVehicle>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_vehicle`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EVehicleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EVehicleTableHandle`], which mediates access to the table `dnd_5_e_vehicle`.
    fn dnd_5_e_vehicle(&self) -> Dnd5EVehicleTableHandle<'_>;
}

impl Dnd5EVehicleTableAccess for super::RemoteTables {
    fn dnd_5_e_vehicle(&self) -> Dnd5EVehicleTableHandle<'_> {
        Dnd5EVehicleTableHandle {
            imp: self.imp.get_table::<Dnd5EVehicle>("dnd_5_e_vehicle"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EVehicleInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EVehicleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EVehicleTableHandle<'ctx> {
    type Row = Dnd5EVehicle;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EVehicle> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EVehicleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EVehicleInsertCallbackId {
        Dnd5EVehicleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EVehicleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EVehicleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EVehicleDeleteCallbackId {
        Dnd5EVehicleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EVehicleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EVehicleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EVehicleTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EVehicleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EVehicleUpdateCallbackId {
        Dnd5EVehicleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EVehicleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_vehicle`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EVehicleIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_vehicle().id().find(...)`.
pub struct Dnd5EVehicleIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EVehicle, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EVehicleTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_vehicle`.
    pub fn id(&self) -> Dnd5EVehicleIdUnique<'ctx> {
        Dnd5EVehicleIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EVehicleIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EVehicle> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EVehicle>("dnd_5_e_vehicle");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EVehicle>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EVehicle>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EVehicle`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_vehicleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EVehicle`.
    fn dnd_5_e_vehicle(&self) -> __sdk::__query_builder::Table<Dnd5EVehicle>;
}

impl dnd_5_e_vehicleQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_vehicle(&self) -> __sdk::__query_builder::Table<Dnd5EVehicle> {
        __sdk::__query_builder::Table::new("dnd_5_e_vehicle")
    }
}
