// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_trap_hazard_type::Dnd5ETrapHazard;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_trap_hazard`.
///
/// Obtain a handle from the [`Dnd5ETrapHazardTableAccess::dnd_5_e_trap_hazard`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_trap_hazard()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_trap_hazard().on_insert(...)`.
pub struct Dnd5ETrapHazardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ETrapHazard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_trap_hazard`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ETrapHazardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ETrapHazardTableHandle`], which mediates access to the table `dnd_5_e_trap_hazard`.
    fn dnd_5_e_trap_hazard(&self) -> Dnd5ETrapHazardTableHandle<'_>;
}

impl Dnd5ETrapHazardTableAccess for super::RemoteTables {
    fn dnd_5_e_trap_hazard(&self) -> Dnd5ETrapHazardTableHandle<'_> {
        Dnd5ETrapHazardTableHandle {
            imp: self.imp.get_table::<Dnd5ETrapHazard>("dnd_5_e_trap_hazard"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ETrapHazardInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ETrapHazardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ETrapHazardTableHandle<'ctx> {
    type Row = Dnd5ETrapHazard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ETrapHazard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ETrapHazardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ETrapHazardInsertCallbackId {
        Dnd5ETrapHazardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ETrapHazardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ETrapHazardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ETrapHazardDeleteCallbackId {
        Dnd5ETrapHazardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ETrapHazardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ETrapHazardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ETrapHazardTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ETrapHazardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ETrapHazardUpdateCallbackId {
        Dnd5ETrapHazardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ETrapHazardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_trap_hazard`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ETrapHazardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_trap_hazard().id().find(...)`.
pub struct Dnd5ETrapHazardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ETrapHazard, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ETrapHazardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_trap_hazard`.
    pub fn id(&self) -> Dnd5ETrapHazardIdUnique<'ctx> {
        Dnd5ETrapHazardIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ETrapHazardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ETrapHazard> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ETrapHazard>("dnd_5_e_trap_hazard");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ETrapHazard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ETrapHazard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ETrapHazard`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_trap_hazardQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ETrapHazard`.
    fn dnd_5_e_trap_hazard(&self) -> __sdk::__query_builder::Table<Dnd5ETrapHazard>;
}

impl dnd_5_e_trap_hazardQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_trap_hazard(&self) -> __sdk::__query_builder::Table<Dnd5ETrapHazard> {
        __sdk::__query_builder::Table::new("dnd_5_e_trap_hazard")
    }
}
