// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EPsionic {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub kind: String,
    pub order_name: Option<String>,
    pub focus: Option<String>,
    pub description: String,
    pub modes: String,
}

impl __sdk::InModule for Dnd5EPsionic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EPsionic`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EPsionicCols {
    pub id: __sdk::__query_builder::Col<Dnd5EPsionic, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
    pub kind: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
    pub order_name: __sdk::__query_builder::Col<Dnd5EPsionic, Option<String>>,
    pub focus: __sdk::__query_builder::Col<Dnd5EPsionic, Option<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
    pub modes: __sdk::__query_builder::Col<Dnd5EPsionic, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EPsionic {
    type Cols = Dnd5EPsionicCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EPsionicCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            order_name: __sdk::__query_builder::Col::new(table_name, "order_name"),
            focus: __sdk::__query_builder::Col::new(table_name, "focus"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            modes: __sdk::__query_builder::Col::new(table_name, "modes"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EPsionic`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EPsionicIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EPsionic, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EPsionic, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EPsionic {
    type IxCols = Dnd5EPsionicIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EPsionicIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EPsionic {}
