// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_type::Ability;
use super::caster_progression_type::CasterProgression;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EClass {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub edition: Option<String>,
    pub hit_die: u8,
    pub saving_throws: Vec<Ability>,
    pub spellcasting_ability: Option<Ability>,
    pub caster_progression: Option<CasterProgression>,
    pub prepared_spells_formula: Option<String>,
    pub prepared_spells_progression: Vec<u8>,
    pub cantrip_progression: Vec<u8>,
    pub class_features: Vec<String>,
    pub subclass_title: Option<String>,
}

impl __sdk::InModule for Dnd5EClass {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EClass`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EClassCols {
    pub id: __sdk::__query_builder::Col<Dnd5EClass, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5EClass, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EClass, String>,
    pub edition: __sdk::__query_builder::Col<Dnd5EClass, Option<String>>,
    pub hit_die: __sdk::__query_builder::Col<Dnd5EClass, u8>,
    pub saving_throws: __sdk::__query_builder::Col<Dnd5EClass, Vec<Ability>>,
    pub spellcasting_ability: __sdk::__query_builder::Col<Dnd5EClass, Option<Ability>>,
    pub caster_progression: __sdk::__query_builder::Col<Dnd5EClass, Option<CasterProgression>>,
    pub prepared_spells_formula: __sdk::__query_builder::Col<Dnd5EClass, Option<String>>,
    pub prepared_spells_progression: __sdk::__query_builder::Col<Dnd5EClass, Vec<u8>>,
    pub cantrip_progression: __sdk::__query_builder::Col<Dnd5EClass, Vec<u8>>,
    pub class_features: __sdk::__query_builder::Col<Dnd5EClass, Vec<String>>,
    pub subclass_title: __sdk::__query_builder::Col<Dnd5EClass, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Dnd5EClass {
    type Cols = Dnd5EClassCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EClassCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            edition: __sdk::__query_builder::Col::new(table_name, "edition"),
            hit_die: __sdk::__query_builder::Col::new(table_name, "hit_die"),
            saving_throws: __sdk::__query_builder::Col::new(table_name, "saving_throws"),
            spellcasting_ability: __sdk::__query_builder::Col::new(
                table_name,
                "spellcasting_ability",
            ),
            caster_progression: __sdk::__query_builder::Col::new(table_name, "caster_progression"),
            prepared_spells_formula: __sdk::__query_builder::Col::new(
                table_name,
                "prepared_spells_formula",
            ),
            prepared_spells_progression: __sdk::__query_builder::Col::new(
                table_name,
                "prepared_spells_progression",
            ),
            cantrip_progression: __sdk::__query_builder::Col::new(
                table_name,
                "cantrip_progression",
            ),
            class_features: __sdk::__query_builder::Col::new(table_name, "class_features"),
            subclass_title: __sdk::__query_builder::Col::new(table_name, "subclass_title"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EClass`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EClassIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EClass, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EClass {
    type IxCols = Dnd5EClassIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EClassIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EClass {}
