// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::creature_size_type::CreatureSize;
use super::dnd_5_e_object_type::Dnd5EObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_object`.
///
/// Obtain a handle from the [`Dnd5EObjectTableAccess::dnd_5_e_object`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_object()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_object().on_insert(...)`.
pub struct Dnd5EObjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_object`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EObjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EObjectTableHandle`], which mediates access to the table `dnd_5_e_object`.
    fn dnd_5_e_object(&self) -> Dnd5EObjectTableHandle<'_>;
}

impl Dnd5EObjectTableAccess for super::RemoteTables {
    fn dnd_5_e_object(&self) -> Dnd5EObjectTableHandle<'_> {
        Dnd5EObjectTableHandle {
            imp: self.imp.get_table::<Dnd5EObject>("dnd_5_e_object"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EObjectInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EObjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EObjectTableHandle<'ctx> {
    type Row = Dnd5EObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EObjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EObjectInsertCallbackId {
        Dnd5EObjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EObjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EObjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EObjectDeleteCallbackId {
        Dnd5EObjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EObjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EObjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EObjectTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EObjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EObjectUpdateCallbackId {
        Dnd5EObjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EObjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_object`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EObjectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_object().id().find(...)`.
pub struct Dnd5EObjectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EObjectTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_object`.
    pub fn id(&self) -> Dnd5EObjectIdUnique<'ctx> {
        Dnd5EObjectIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EObjectIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EObject> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_object`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EObjectKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_object().key().find(...)`.
pub struct Dnd5EObjectKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EObject, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EObjectTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_object`.
    pub fn key(&self) -> Dnd5EObjectKeyUnique<'ctx> {
        Dnd5EObjectKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EObjectKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EObject> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EObject>("dnd_5_e_object");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EObject`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_objectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EObject`.
    fn dnd_5_e_object(&self) -> __sdk::__query_builder::Table<Dnd5EObject>;
}

impl dnd_5_e_objectQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_object(&self) -> __sdk::__query_builder::Table<Dnd5EObject> {
        __sdk::__query_builder::Table::new("dnd_5_e_object")
    }
}
