// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_sense_type::Dnd5ESense;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_sense`.
///
/// Obtain a handle from the [`Dnd5ESenseTableAccess::dnd_5_e_sense`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_sense()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_sense().on_insert(...)`.
pub struct Dnd5ESenseTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ESense>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_sense`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ESenseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ESenseTableHandle`], which mediates access to the table `dnd_5_e_sense`.
    fn dnd_5_e_sense(&self) -> Dnd5ESenseTableHandle<'_>;
}

impl Dnd5ESenseTableAccess for super::RemoteTables {
    fn dnd_5_e_sense(&self) -> Dnd5ESenseTableHandle<'_> {
        Dnd5ESenseTableHandle {
            imp: self.imp.get_table::<Dnd5ESense>("dnd_5_e_sense"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ESenseInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ESenseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ESenseTableHandle<'ctx> {
    type Row = Dnd5ESense;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ESense> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ESenseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESenseInsertCallbackId {
        Dnd5ESenseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ESenseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ESenseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESenseDeleteCallbackId {
        Dnd5ESenseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ESenseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ESenseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ESenseTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ESenseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ESenseUpdateCallbackId {
        Dnd5ESenseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ESenseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_sense`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ESenseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_sense().id().find(...)`.
pub struct Dnd5ESenseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ESense, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ESenseTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_sense`.
    pub fn id(&self) -> Dnd5ESenseIdUnique<'ctx> {
        Dnd5ESenseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ESenseIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ESense> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_sense`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ESenseKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_sense().key().find(...)`.
pub struct Dnd5ESenseKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ESense, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ESenseTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_sense`.
    pub fn key(&self) -> Dnd5ESenseKeyUnique<'ctx> {
        Dnd5ESenseKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ESenseKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5ESense> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ESense>("dnd_5_e_sense");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ESense>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ESense>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ESense`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_senseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ESense`.
    fn dnd_5_e_sense(&self) -> __sdk::__query_builder::Table<Dnd5ESense>;
}

impl dnd_5_e_senseQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_sense(&self) -> __sdk::__query_builder::Table<Dnd5ESense> {
        __sdk::__query_builder::Table::new("dnd_5_e_sense")
    }
}
