// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_type::Ability;
use super::dnd_5_e_skill_type::Dnd5ESkill;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_skill`.
///
/// Obtain a handle from the [`Dnd5ESkillTableAccess::dnd_5_e_skill`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_skill()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_skill().on_insert(...)`.
pub struct Dnd5ESkillTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ESkill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_skill`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ESkillTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ESkillTableHandle`], which mediates access to the table `dnd_5_e_skill`.
    fn dnd_5_e_skill(&self) -> Dnd5ESkillTableHandle<'_>;
}

impl Dnd5ESkillTableAccess for super::RemoteTables {
    fn dnd_5_e_skill(&self) -> Dnd5ESkillTableHandle<'_> {
        Dnd5ESkillTableHandle {
            imp: self.imp.get_table::<Dnd5ESkill>("dnd_5_e_skill"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ESkillInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ESkillDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ESkillTableHandle<'ctx> {
    type Row = Dnd5ESkill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ESkill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ESkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESkillInsertCallbackId {
        Dnd5ESkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ESkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ESkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESkillDeleteCallbackId {
        Dnd5ESkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ESkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ESkillUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ESkillTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ESkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ESkillUpdateCallbackId {
        Dnd5ESkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ESkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_skill`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ESkillIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_skill().id().find(...)`.
pub struct Dnd5ESkillIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ESkill, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ESkillTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_skill`.
    pub fn id(&self) -> Dnd5ESkillIdUnique<'ctx> {
        Dnd5ESkillIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ESkillIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ESkill> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_skill`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ESkillKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_skill().key().find(...)`.
pub struct Dnd5ESkillKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ESkill, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ESkillTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_skill`.
    pub fn key(&self) -> Dnd5ESkillKeyUnique<'ctx> {
        Dnd5ESkillKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ESkillKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5ESkill> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ESkill>("dnd_5_e_skill");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ESkill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ESkill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ESkill`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_skillQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ESkill`.
    fn dnd_5_e_skill(&self) -> __sdk::__query_builder::Table<Dnd5ESkill>;
}

impl dnd_5_e_skillQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_skill(&self) -> __sdk::__query_builder::Table<Dnd5ESkill> {
        __sdk::__query_builder::Table::new("dnd_5_e_skill")
    }
}
