// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_class_feature_type::Dnd5EClassFeature;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_class_feature`.
///
/// Obtain a handle from the [`Dnd5EClassFeatureTableAccess::dnd_5_e_class_feature`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_class_feature()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_class_feature().on_insert(...)`.
pub struct Dnd5EClassFeatureTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EClassFeature>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_class_feature`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EClassFeatureTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EClassFeatureTableHandle`], which mediates access to the table `dnd_5_e_class_feature`.
    fn dnd_5_e_class_feature(&self) -> Dnd5EClassFeatureTableHandle<'_>;
}

impl Dnd5EClassFeatureTableAccess for super::RemoteTables {
    fn dnd_5_e_class_feature(&self) -> Dnd5EClassFeatureTableHandle<'_> {
        Dnd5EClassFeatureTableHandle {
            imp: self
                .imp
                .get_table::<Dnd5EClassFeature>("dnd_5_e_class_feature"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EClassFeatureInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EClassFeatureDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EClassFeatureTableHandle<'ctx> {
    type Row = Dnd5EClassFeature;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EClassFeature> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EClassFeatureInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassFeatureInsertCallbackId {
        Dnd5EClassFeatureInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EClassFeatureInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EClassFeatureDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassFeatureDeleteCallbackId {
        Dnd5EClassFeatureDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EClassFeatureDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EClassFeatureUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EClassFeatureTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EClassFeatureUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EClassFeatureUpdateCallbackId {
        Dnd5EClassFeatureUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EClassFeatureUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_class_feature`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EClassFeatureIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_class_feature().id().find(...)`.
pub struct Dnd5EClassFeatureIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EClassFeature, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EClassFeatureTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_class_feature`.
    pub fn id(&self) -> Dnd5EClassFeatureIdUnique<'ctx> {
        Dnd5EClassFeatureIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EClassFeatureIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EClassFeature> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_class_feature`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EClassFeatureKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_class_feature().key().find(...)`.
pub struct Dnd5EClassFeatureKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EClassFeature, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EClassFeatureTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_class_feature`.
    pub fn key(&self) -> Dnd5EClassFeatureKeyUnique<'ctx> {
        Dnd5EClassFeatureKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EClassFeatureKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EClassFeature> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EClassFeature>("dnd_5_e_class_feature");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EClassFeature>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EClassFeature>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EClassFeature`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_class_featureQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EClassFeature`.
    fn dnd_5_e_class_feature(&self) -> __sdk::__query_builder::Table<Dnd5EClassFeature>;
}

impl dnd_5_e_class_featureQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_class_feature(&self) -> __sdk::__query_builder::Table<Dnd5EClassFeature> {
        __sdk::__query_builder::Table::new("dnd_5_e_class_feature")
    }
}
