// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_variant_rule_type::Dnd5EVariantRule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_variant_rule`.
///
/// Obtain a handle from the [`Dnd5EVariantRuleTableAccess::dnd_5_e_variant_rule`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_variant_rule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_variant_rule().on_insert(...)`.
pub struct Dnd5EVariantRuleTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EVariantRule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_variant_rule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EVariantRuleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EVariantRuleTableHandle`], which mediates access to the table `dnd_5_e_variant_rule`.
    fn dnd_5_e_variant_rule(&self) -> Dnd5EVariantRuleTableHandle<'_>;
}

impl Dnd5EVariantRuleTableAccess for super::RemoteTables {
    fn dnd_5_e_variant_rule(&self) -> Dnd5EVariantRuleTableHandle<'_> {
        Dnd5EVariantRuleTableHandle {
            imp: self
                .imp
                .get_table::<Dnd5EVariantRule>("dnd_5_e_variant_rule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EVariantRuleInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EVariantRuleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EVariantRuleTableHandle<'ctx> {
    type Row = Dnd5EVariantRule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EVariantRule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EVariantRuleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EVariantRuleInsertCallbackId {
        Dnd5EVariantRuleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EVariantRuleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EVariantRuleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EVariantRuleDeleteCallbackId {
        Dnd5EVariantRuleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EVariantRuleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EVariantRuleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EVariantRuleTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EVariantRuleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EVariantRuleUpdateCallbackId {
        Dnd5EVariantRuleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EVariantRuleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_variant_rule`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EVariantRuleIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_variant_rule().id().find(...)`.
pub struct Dnd5EVariantRuleIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EVariantRule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EVariantRuleTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_variant_rule`.
    pub fn id(&self) -> Dnd5EVariantRuleIdUnique<'ctx> {
        Dnd5EVariantRuleIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EVariantRuleIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EVariantRule> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_variant_rule`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EVariantRuleKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_variant_rule().key().find(...)`.
pub struct Dnd5EVariantRuleKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EVariantRule, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EVariantRuleTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_variant_rule`.
    pub fn key(&self) -> Dnd5EVariantRuleKeyUnique<'ctx> {
        Dnd5EVariantRuleKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EVariantRuleKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EVariantRule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EVariantRule>("dnd_5_e_variant_rule");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EVariantRule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EVariantRule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EVariantRule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_variant_ruleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EVariantRule`.
    fn dnd_5_e_variant_rule(&self) -> __sdk::__query_builder::Table<Dnd5EVariantRule>;
}

impl dnd_5_e_variant_ruleQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_variant_rule(&self) -> __sdk::__query_builder::Table<Dnd5EVariantRule> {
        __sdk::__query_builder::Table::new("dnd_5_e_variant_rule")
    }
}
