// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ERecipe {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub recipe_type: Option<String>,
    pub dish_types: Vec<String>,
    pub diet: Option<String>,
    pub serves: Option<String>,
    pub ingredients: String,
    pub instructions: String,
}

impl __sdk::InModule for Dnd5ERecipe {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ERecipe`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ERecipeCols {
    pub id: __sdk::__query_builder::Col<Dnd5ERecipe, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ERecipe, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ERecipe, String>,
    pub recipe_type: __sdk::__query_builder::Col<Dnd5ERecipe, Option<String>>,
    pub dish_types: __sdk::__query_builder::Col<Dnd5ERecipe, Vec<String>>,
    pub diet: __sdk::__query_builder::Col<Dnd5ERecipe, Option<String>>,
    pub serves: __sdk::__query_builder::Col<Dnd5ERecipe, Option<String>>,
    pub ingredients: __sdk::__query_builder::Col<Dnd5ERecipe, String>,
    pub instructions: __sdk::__query_builder::Col<Dnd5ERecipe, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ERecipe {
    type Cols = Dnd5ERecipeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ERecipeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            recipe_type: __sdk::__query_builder::Col::new(table_name, "recipe_type"),
            dish_types: __sdk::__query_builder::Col::new(table_name, "dish_types"),
            diet: __sdk::__query_builder::Col::new(table_name, "diet"),
            serves: __sdk::__query_builder::Col::new(table_name, "serves"),
            ingredients: __sdk::__query_builder::Col::new(table_name, "ingredients"),
            instructions: __sdk::__query_builder::Col::new(table_name, "instructions"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ERecipe`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ERecipeIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ERecipe, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ERecipe {
    type IxCols = Dnd5ERecipeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ERecipeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ERecipe {}
