// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::creature_size_type::CreatureSize;
use super::creature_type_type::CreatureType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EMonster {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub size: CreatureSize,
    pub creature_type: CreatureType,
    pub cr: String,
    pub ac: u8,
    pub hp_average: u16,
    pub hp_formula: String,
    pub speed_walk: u16,
    pub speed_fly: u16,
    pub speed_swim: u16,
    pub str_score: u8,
    pub dex_score: u8,
    pub con_score: u8,
    pub int_score: u8,
    pub wis_score: u8,
    pub cha_score: u8,
    pub description: String,
}

impl __sdk::InModule for Dnd5EMonster {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EMonster`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EMonsterCols {
    pub id: __sdk::__query_builder::Col<Dnd5EMonster, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EMonster, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EMonster, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EMonster, String>,
    pub size: __sdk::__query_builder::Col<Dnd5EMonster, CreatureSize>,
    pub creature_type: __sdk::__query_builder::Col<Dnd5EMonster, CreatureType>,
    pub cr: __sdk::__query_builder::Col<Dnd5EMonster, String>,
    pub ac: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub hp_average: __sdk::__query_builder::Col<Dnd5EMonster, u16>,
    pub hp_formula: __sdk::__query_builder::Col<Dnd5EMonster, String>,
    pub speed_walk: __sdk::__query_builder::Col<Dnd5EMonster, u16>,
    pub speed_fly: __sdk::__query_builder::Col<Dnd5EMonster, u16>,
    pub speed_swim: __sdk::__query_builder::Col<Dnd5EMonster, u16>,
    pub str_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub dex_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub con_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub int_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub wis_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub cha_score: __sdk::__query_builder::Col<Dnd5EMonster, u8>,
    pub description: __sdk::__query_builder::Col<Dnd5EMonster, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EMonster {
    type Cols = Dnd5EMonsterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EMonsterCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            creature_type: __sdk::__query_builder::Col::new(table_name, "creature_type"),
            cr: __sdk::__query_builder::Col::new(table_name, "cr"),
            ac: __sdk::__query_builder::Col::new(table_name, "ac"),
            hp_average: __sdk::__query_builder::Col::new(table_name, "hp_average"),
            hp_formula: __sdk::__query_builder::Col::new(table_name, "hp_formula"),
            speed_walk: __sdk::__query_builder::Col::new(table_name, "speed_walk"),
            speed_fly: __sdk::__query_builder::Col::new(table_name, "speed_fly"),
            speed_swim: __sdk::__query_builder::Col::new(table_name, "speed_swim"),
            str_score: __sdk::__query_builder::Col::new(table_name, "str_score"),
            dex_score: __sdk::__query_builder::Col::new(table_name, "dex_score"),
            con_score: __sdk::__query_builder::Col::new(table_name, "con_score"),
            int_score: __sdk::__query_builder::Col::new(table_name, "int_score"),
            wis_score: __sdk::__query_builder::Col::new(table_name, "wis_score"),
            cha_score: __sdk::__query_builder::Col::new(table_name, "cha_score"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EMonster`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EMonsterIxCols {
    pub cr: __sdk::__query_builder::IxCol<Dnd5EMonster, String>,
    pub id: __sdk::__query_builder::IxCol<Dnd5EMonster, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EMonster, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EMonster {
    type IxCols = Dnd5EMonsterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EMonsterIxCols {
            cr: __sdk::__query_builder::IxCol::new(table_name, "cr"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EMonster {}
