// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::creature_size_type::CreatureSize;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EObject {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub size: Vec<CreatureSize>,
    pub object_type: Option<String>,
    pub ac: Option<u16>,
    pub hp: Option<u16>,
    pub description: String,
    pub action_description: String,
}

impl __sdk::InModule for Dnd5EObject {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EObject`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EObjectCols {
    pub id: __sdk::__query_builder::Col<Dnd5EObject, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EObject, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EObject, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EObject, String>,
    pub size: __sdk::__query_builder::Col<Dnd5EObject, Vec<CreatureSize>>,
    pub object_type: __sdk::__query_builder::Col<Dnd5EObject, Option<String>>,
    pub ac: __sdk::__query_builder::Col<Dnd5EObject, Option<u16>>,
    pub hp: __sdk::__query_builder::Col<Dnd5EObject, Option<u16>>,
    pub description: __sdk::__query_builder::Col<Dnd5EObject, String>,
    pub action_description: __sdk::__query_builder::Col<Dnd5EObject, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EObject {
    type Cols = Dnd5EObjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EObjectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            object_type: __sdk::__query_builder::Col::new(table_name, "object_type"),
            ac: __sdk::__query_builder::Col::new(table_name, "ac"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            action_description: __sdk::__query_builder::Col::new(table_name, "action_description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EObject`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EObjectIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EObject, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EObject, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EObject {
    type IxCols = Dnd5EObjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EObjectIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EObject {}
