// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::language_grant_type::LanguageGrant;
use super::skill_grant_type::SkillGrant;
use super::tool_grant_type::ToolGrant;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EBackground {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub skill_proficiencies: Vec<SkillGrant>,
    pub tool_proficiencies: Vec<ToolGrant>,
    pub language_proficiencies: Vec<LanguageGrant>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EBackground {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EBackground`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EBackgroundCols {
    pub id: __sdk::__query_builder::Col<Dnd5EBackground, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EBackground, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EBackground, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EBackground, String>,
    pub skill_proficiencies: __sdk::__query_builder::Col<Dnd5EBackground, Vec<SkillGrant>>,
    pub tool_proficiencies: __sdk::__query_builder::Col<Dnd5EBackground, Vec<ToolGrant>>,
    pub language_proficiencies: __sdk::__query_builder::Col<Dnd5EBackground, Vec<LanguageGrant>>,
    pub description: __sdk::__query_builder::Col<Dnd5EBackground, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EBackground {
    type Cols = Dnd5EBackgroundCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EBackgroundCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            skill_proficiencies: __sdk::__query_builder::Col::new(
                table_name,
                "skill_proficiencies",
            ),
            tool_proficiencies: __sdk::__query_builder::Col::new(table_name, "tool_proficiencies"),
            language_proficiencies: __sdk::__query_builder::Col::new(
                table_name,
                "language_proficiencies",
            ),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EBackground`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EBackgroundIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EBackground, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EBackground, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EBackground {
    type IxCols = Dnd5EBackgroundIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EBackgroundIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EBackground {}
