// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_type::Ability;
use super::dnd_5_e_spell_type::Dnd5ESpell;
use super::spell_school_type::SpellSchool;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_spell`.
///
/// Obtain a handle from the [`Dnd5ESpellTableAccess::dnd_5_e_spell`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_spell()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_spell().on_insert(...)`.
pub struct Dnd5ESpellTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ESpell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_spell`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ESpellTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ESpellTableHandle`], which mediates access to the table `dnd_5_e_spell`.
    fn dnd_5_e_spell(&self) -> Dnd5ESpellTableHandle<'_>;
}

impl Dnd5ESpellTableAccess for super::RemoteTables {
    fn dnd_5_e_spell(&self) -> Dnd5ESpellTableHandle<'_> {
        Dnd5ESpellTableHandle {
            imp: self.imp.get_table::<Dnd5ESpell>("dnd_5_e_spell"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ESpellInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ESpellDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ESpellTableHandle<'ctx> {
    type Row = Dnd5ESpell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ESpell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ESpellInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESpellInsertCallbackId {
        Dnd5ESpellInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ESpellInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ESpellDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ESpellDeleteCallbackId {
        Dnd5ESpellDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ESpellDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ESpellUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ESpellTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ESpellUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ESpellUpdateCallbackId {
        Dnd5ESpellUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ESpellUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_spell`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ESpellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_spell().id().find(...)`.
pub struct Dnd5ESpellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ESpell, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ESpellTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_spell`.
    pub fn id(&self) -> Dnd5ESpellIdUnique<'ctx> {
        Dnd5ESpellIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ESpellIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ESpell> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ESpell>("dnd_5_e_spell");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ESpell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ESpell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ESpell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_spellQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ESpell`.
    fn dnd_5_e_spell(&self) -> __sdk::__query_builder::Table<Dnd5ESpell>;
}

impl dnd_5_e_spellQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_spell(&self) -> __sdk::__query_builder::Table<Dnd5ESpell> {
        __sdk::__query_builder::Table::new("dnd_5_e_spell")
    }
}
