// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::alignment_type::Alignment;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EDeity {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub pantheon: Option<String>,
    pub alignment: Vec<Alignment>,
    pub category: Option<String>,
    pub domains: Vec<String>,
    pub province: Option<String>,
    pub title: Option<String>,
    pub symbol: Option<String>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EDeity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EDeity`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EDeityCols {
    pub id: __sdk::__query_builder::Col<Dnd5EDeity, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5EDeity, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EDeity, String>,
    pub pantheon: __sdk::__query_builder::Col<Dnd5EDeity, Option<String>>,
    pub alignment: __sdk::__query_builder::Col<Dnd5EDeity, Vec<Alignment>>,
    pub category: __sdk::__query_builder::Col<Dnd5EDeity, Option<String>>,
    pub domains: __sdk::__query_builder::Col<Dnd5EDeity, Vec<String>>,
    pub province: __sdk::__query_builder::Col<Dnd5EDeity, Option<String>>,
    pub title: __sdk::__query_builder::Col<Dnd5EDeity, Option<String>>,
    pub symbol: __sdk::__query_builder::Col<Dnd5EDeity, Option<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5EDeity, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EDeity {
    type Cols = Dnd5EDeityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EDeityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            pantheon: __sdk::__query_builder::Col::new(table_name, "pantheon"),
            alignment: __sdk::__query_builder::Col::new(table_name, "alignment"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            domains: __sdk::__query_builder::Col::new(table_name, "domains"),
            province: __sdk::__query_builder::Col::new(table_name, "province"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EDeity`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EDeityIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EDeity, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EDeity {
    type IxCols = Dnd5EDeityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EDeityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EDeity {}
