// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_grant_type::AbilityGrant;
use super::creature_size_type::CreatureSize;
use super::language_grant_type::LanguageGrant;
use super::speed_type::Speed;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ERace {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub size: CreatureSize,
    pub speed: Speed,
    pub ability_bonuses: Vec<AbilityGrant>,
    pub language_proficiencies: Vec<LanguageGrant>,
    pub description: String,
}

impl __sdk::InModule for Dnd5ERace {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ERace`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ERaceCols {
    pub id: __sdk::__query_builder::Col<Dnd5ERace, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ERace, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ERace, String>,
    pub size: __sdk::__query_builder::Col<Dnd5ERace, CreatureSize>,
    pub speed: __sdk::__query_builder::Col<Dnd5ERace, Speed>,
    pub ability_bonuses: __sdk::__query_builder::Col<Dnd5ERace, Vec<AbilityGrant>>,
    pub language_proficiencies: __sdk::__query_builder::Col<Dnd5ERace, Vec<LanguageGrant>>,
    pub description: __sdk::__query_builder::Col<Dnd5ERace, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ERace {
    type Cols = Dnd5ERaceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ERaceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            ability_bonuses: __sdk::__query_builder::Col::new(table_name, "ability_bonuses"),
            language_proficiencies: __sdk::__query_builder::Col::new(
                table_name,
                "language_proficiencies",
            ),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ERace`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ERaceIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ERace, u64>,
    pub size: __sdk::__query_builder::IxCol<Dnd5ERace, CreatureSize>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ERace {
    type IxCols = Dnd5ERaceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ERaceIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            size: __sdk::__query_builder::IxCol::new(table_name, "size"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ERace {}
