// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_optional_feature_type::Dnd5EOptionalFeature;
use super::optional_feature_prereq_type::OptionalFeaturePrereq;
use super::optional_feature_type_type::OptionalFeatureType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_optional_feature`.
///
/// Obtain a handle from the [`Dnd5EOptionalFeatureTableAccess::dnd_5_e_optional_feature`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_optional_feature()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_optional_feature().on_insert(...)`.
pub struct Dnd5EOptionalFeatureTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EOptionalFeature>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_optional_feature`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EOptionalFeatureTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EOptionalFeatureTableHandle`], which mediates access to the table `dnd_5_e_optional_feature`.
    fn dnd_5_e_optional_feature(&self) -> Dnd5EOptionalFeatureTableHandle<'_>;
}

impl Dnd5EOptionalFeatureTableAccess for super::RemoteTables {
    fn dnd_5_e_optional_feature(&self) -> Dnd5EOptionalFeatureTableHandle<'_> {
        Dnd5EOptionalFeatureTableHandle {
            imp: self
                .imp
                .get_table::<Dnd5EOptionalFeature>("dnd_5_e_optional_feature"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EOptionalFeatureInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EOptionalFeatureDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EOptionalFeatureTableHandle<'ctx> {
    type Row = Dnd5EOptionalFeature;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EOptionalFeature> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EOptionalFeatureInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EOptionalFeatureInsertCallbackId {
        Dnd5EOptionalFeatureInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EOptionalFeatureInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EOptionalFeatureDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EOptionalFeatureDeleteCallbackId {
        Dnd5EOptionalFeatureDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EOptionalFeatureDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EOptionalFeatureUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EOptionalFeatureTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EOptionalFeatureUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EOptionalFeatureUpdateCallbackId {
        Dnd5EOptionalFeatureUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EOptionalFeatureUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_optional_feature`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EOptionalFeatureIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_optional_feature().id().find(...)`.
pub struct Dnd5EOptionalFeatureIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EOptionalFeature, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EOptionalFeatureTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_optional_feature`.
    pub fn id(&self) -> Dnd5EOptionalFeatureIdUnique<'ctx> {
        Dnd5EOptionalFeatureIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EOptionalFeatureIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EOptionalFeature> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EOptionalFeature>("dnd_5_e_optional_feature");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EOptionalFeature>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EOptionalFeature>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EOptionalFeature`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_optional_featureQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EOptionalFeature`.
    fn dnd_5_e_optional_feature(&self) -> __sdk::__query_builder::Table<Dnd5EOptionalFeature>;
}

impl dnd_5_e_optional_featureQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_optional_feature(&self) -> __sdk::__query_builder::Table<Dnd5EOptionalFeature> {
        __sdk::__query_builder::Table::new("dnd_5_e_optional_feature")
    }
}
