// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_deck_type::Dnd5EDeck;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_deck`.
///
/// Obtain a handle from the [`Dnd5EDeckTableAccess::dnd_5_e_deck`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_deck()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_deck().on_insert(...)`.
pub struct Dnd5EDeckTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EDeck>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_deck`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EDeckTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EDeckTableHandle`], which mediates access to the table `dnd_5_e_deck`.
    fn dnd_5_e_deck(&self) -> Dnd5EDeckTableHandle<'_>;
}

impl Dnd5EDeckTableAccess for super::RemoteTables {
    fn dnd_5_e_deck(&self) -> Dnd5EDeckTableHandle<'_> {
        Dnd5EDeckTableHandle {
            imp: self.imp.get_table::<Dnd5EDeck>("dnd_5_e_deck"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EDeckInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EDeckDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EDeckTableHandle<'ctx> {
    type Row = Dnd5EDeck;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EDeck> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EDeckInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeckInsertCallbackId {
        Dnd5EDeckInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EDeckInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EDeckDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeckDeleteCallbackId {
        Dnd5EDeckDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EDeckDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EDeckUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EDeckTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EDeckUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeckUpdateCallbackId {
        Dnd5EDeckUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EDeckUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_deck`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EDeckIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_deck().id().find(...)`.
pub struct Dnd5EDeckIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EDeck, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EDeckTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_deck`.
    pub fn id(&self) -> Dnd5EDeckIdUnique<'ctx> {
        Dnd5EDeckIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EDeckIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EDeck> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_deck`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EDeckKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_deck().key().find(...)`.
pub struct Dnd5EDeckKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EDeck, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EDeckTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_deck`.
    pub fn key(&self) -> Dnd5EDeckKeyUnique<'ctx> {
        Dnd5EDeckKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EDeckKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EDeck> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EDeck>("dnd_5_e_deck");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EDeck>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EDeck>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EDeck`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_deckQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EDeck`.
    fn dnd_5_e_deck(&self) -> __sdk::__query_builder::Table<Dnd5EDeck>;
}

impl dnd_5_e_deckQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_deck(&self) -> __sdk::__query_builder::Table<Dnd5EDeck> {
        __sdk::__query_builder::Table::new("dnd_5_e_deck")
    }
}
