// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_item_type::Dnd5EItem;
use super::item_rarity_type::ItemRarity;
use super::item_type_type::ItemType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_item`.
///
/// Obtain a handle from the [`Dnd5EItemTableAccess::dnd_5_e_item`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_item().on_insert(...)`.
pub struct Dnd5EItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EItemTableHandle`], which mediates access to the table `dnd_5_e_item`.
    fn dnd_5_e_item(&self) -> Dnd5EItemTableHandle<'_>;
}

impl Dnd5EItemTableAccess for super::RemoteTables {
    fn dnd_5_e_item(&self) -> Dnd5EItemTableHandle<'_> {
        Dnd5EItemTableHandle {
            imp: self.imp.get_table::<Dnd5EItem>("dnd_5_e_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EItemInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EItemTableHandle<'ctx> {
    type Row = Dnd5EItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EItemInsertCallbackId {
        Dnd5EItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EItemDeleteCallbackId {
        Dnd5EItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EItemTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EItemUpdateCallbackId {
        Dnd5EItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_item`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_item().id().find(...)`.
pub struct Dnd5EItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_item`.
    pub fn id(&self) -> Dnd5EItemIdUnique<'ctx> {
        Dnd5EItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EItem> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_item`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EItemKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_item().key().find(...)`.
pub struct Dnd5EItemKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EItem, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EItemTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_item`.
    pub fn key(&self) -> Dnd5EItemKeyUnique<'ctx> {
        Dnd5EItemKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EItemKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EItem>("dnd_5_e_item");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EItem`.
    fn dnd_5_e_item(&self) -> __sdk::__query_builder::Table<Dnd5EItem>;
}

impl dnd_5_e_itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_item(&self) -> __sdk::__query_builder::Table<Dnd5EItem> {
        __sdk::__query_builder::Table::new("dnd_5_e_item")
    }
}
