// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_reward_type::Dnd5EReward;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_reward`.
///
/// Obtain a handle from the [`Dnd5ERewardTableAccess::dnd_5_e_reward`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_reward()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_reward().on_insert(...)`.
pub struct Dnd5ERewardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EReward>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_reward`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ERewardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ERewardTableHandle`], which mediates access to the table `dnd_5_e_reward`.
    fn dnd_5_e_reward(&self) -> Dnd5ERewardTableHandle<'_>;
}

impl Dnd5ERewardTableAccess for super::RemoteTables {
    fn dnd_5_e_reward(&self) -> Dnd5ERewardTableHandle<'_> {
        Dnd5ERewardTableHandle {
            imp: self.imp.get_table::<Dnd5EReward>("dnd_5_e_reward"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ERewardInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ERewardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ERewardTableHandle<'ctx> {
    type Row = Dnd5EReward;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EReward> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ERewardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ERewardInsertCallbackId {
        Dnd5ERewardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ERewardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ERewardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ERewardDeleteCallbackId {
        Dnd5ERewardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ERewardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ERewardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ERewardTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ERewardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ERewardUpdateCallbackId {
        Dnd5ERewardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ERewardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_reward`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ERewardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_reward().id().find(...)`.
pub struct Dnd5ERewardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EReward, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ERewardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_reward`.
    pub fn id(&self) -> Dnd5ERewardIdUnique<'ctx> {
        Dnd5ERewardIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ERewardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EReward> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EReward>("dnd_5_e_reward");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EReward>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EReward>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EReward`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_rewardQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EReward`.
    fn dnd_5_e_reward(&self) -> __sdk::__query_builder::Table<Dnd5EReward>;
}

impl dnd_5_e_rewardQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_reward(&self) -> __sdk::__query_builder::Table<Dnd5EReward> {
        __sdk::__query_builder::Table::new("dnd_5_e_reward")
    }
}
