// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_grant_type::AbilityGrant;
use super::creature_size_type::CreatureSize;
use super::dnd_5_e_race_type::Dnd5ERace;
use super::language_grant_type::LanguageGrant;
use super::speed_type::Speed;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_race`.
///
/// Obtain a handle from the [`Dnd5ERaceTableAccess::dnd_5_e_race`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_race()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_race().on_insert(...)`.
pub struct Dnd5ERaceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ERace>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_race`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ERaceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ERaceTableHandle`], which mediates access to the table `dnd_5_e_race`.
    fn dnd_5_e_race(&self) -> Dnd5ERaceTableHandle<'_>;
}

impl Dnd5ERaceTableAccess for super::RemoteTables {
    fn dnd_5_e_race(&self) -> Dnd5ERaceTableHandle<'_> {
        Dnd5ERaceTableHandle {
            imp: self.imp.get_table::<Dnd5ERace>("dnd_5_e_race"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ERaceInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ERaceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ERaceTableHandle<'ctx> {
    type Row = Dnd5ERace;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ERace> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ERaceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ERaceInsertCallbackId {
        Dnd5ERaceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ERaceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ERaceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ERaceDeleteCallbackId {
        Dnd5ERaceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ERaceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ERaceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ERaceTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ERaceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ERaceUpdateCallbackId {
        Dnd5ERaceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ERaceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_race`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ERaceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_race().id().find(...)`.
pub struct Dnd5ERaceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ERace, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ERaceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_race`.
    pub fn id(&self) -> Dnd5ERaceIdUnique<'ctx> {
        Dnd5ERaceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ERaceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ERace> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_race`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ERaceKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_race().key().find(...)`.
pub struct Dnd5ERaceKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ERace, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ERaceTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_race`.
    pub fn key(&self) -> Dnd5ERaceKeyUnique<'ctx> {
        Dnd5ERaceKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ERaceKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5ERace> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ERace>("dnd_5_e_race");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ERace>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ERace>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ERace`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_raceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ERace`.
    fn dnd_5_e_race(&self) -> __sdk::__query_builder::Table<Dnd5ERace>;
}

impl dnd_5_e_raceQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_race(&self) -> __sdk::__query_builder::Table<Dnd5ERace> {
        __sdk::__query_builder::Table::new("dnd_5_e_race")
    }
}
