// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ECultBoon {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub kind: String,
    pub subtype: Option<String>,
    pub goal: Option<String>,
    pub cultists: Option<String>,
    pub signature_spells: Option<String>,
    pub ability_text: Option<String>,
    pub description: String,
}

impl __sdk::InModule for Dnd5ECultBoon {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ECultBoon`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ECultBoonCols {
    pub id: __sdk::__query_builder::Col<Dnd5ECultBoon, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ECultBoon, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ECultBoon, String>,
    pub kind: __sdk::__query_builder::Col<Dnd5ECultBoon, String>,
    pub subtype: __sdk::__query_builder::Col<Dnd5ECultBoon, Option<String>>,
    pub goal: __sdk::__query_builder::Col<Dnd5ECultBoon, Option<String>>,
    pub cultists: __sdk::__query_builder::Col<Dnd5ECultBoon, Option<String>>,
    pub signature_spells: __sdk::__query_builder::Col<Dnd5ECultBoon, Option<String>>,
    pub ability_text: __sdk::__query_builder::Col<Dnd5ECultBoon, Option<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5ECultBoon, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ECultBoon {
    type Cols = Dnd5ECultBoonCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ECultBoonCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            subtype: __sdk::__query_builder::Col::new(table_name, "subtype"),
            goal: __sdk::__query_builder::Col::new(table_name, "goal"),
            cultists: __sdk::__query_builder::Col::new(table_name, "cultists"),
            signature_spells: __sdk::__query_builder::Col::new(table_name, "signature_spells"),
            ability_text: __sdk::__query_builder::Col::new(table_name, "ability_text"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ECultBoon`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ECultBoonIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ECultBoon, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ECultBoon {
    type IxCols = Dnd5ECultBoonIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ECultBoonIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ECultBoon {}
