// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_cult_boon_type::Dnd5ECultBoon;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_cult_boon`.
///
/// Obtain a handle from the [`Dnd5ECultBoonTableAccess::dnd_5_e_cult_boon`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_cult_boon()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_cult_boon().on_insert(...)`.
pub struct Dnd5ECultBoonTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ECultBoon>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_cult_boon`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5ECultBoonTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5ECultBoonTableHandle`], which mediates access to the table `dnd_5_e_cult_boon`.
    fn dnd_5_e_cult_boon(&self) -> Dnd5ECultBoonTableHandle<'_>;
}

impl Dnd5ECultBoonTableAccess for super::RemoteTables {
    fn dnd_5_e_cult_boon(&self) -> Dnd5ECultBoonTableHandle<'_> {
        Dnd5ECultBoonTableHandle {
            imp: self.imp.get_table::<Dnd5ECultBoon>("dnd_5_e_cult_boon"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5ECultBoonInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5ECultBoonDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5ECultBoonTableHandle<'ctx> {
    type Row = Dnd5ECultBoon;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ECultBoon> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5ECultBoonInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ECultBoonInsertCallbackId {
        Dnd5ECultBoonInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5ECultBoonInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5ECultBoonDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5ECultBoonDeleteCallbackId {
        Dnd5ECultBoonDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5ECultBoonDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5ECultBoonUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5ECultBoonTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5ECultBoonUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5ECultBoonUpdateCallbackId {
        Dnd5ECultBoonUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5ECultBoonUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_cult_boon`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5ECultBoonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_cult_boon().id().find(...)`.
pub struct Dnd5ECultBoonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ECultBoon, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5ECultBoonTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_cult_boon`.
    pub fn id(&self) -> Dnd5ECultBoonIdUnique<'ctx> {
        Dnd5ECultBoonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5ECultBoonIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ECultBoon> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ECultBoon>("dnd_5_e_cult_boon");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ECultBoon>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ECultBoon>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ECultBoon`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_cult_boonQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ECultBoon`.
    fn dnd_5_e_cult_boon(&self) -> __sdk::__query_builder::Table<Dnd5ECultBoon>;
}

impl dnd_5_e_cult_boonQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_cult_boon(&self) -> __sdk::__query_builder::Table<Dnd5ECultBoon> {
        __sdk::__query_builder::Table::new("dnd_5_e_cult_boon")
    }
}
