// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ELanguage {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub kind: Option<String>,
    pub script: Option<String>,
    pub origin: Option<String>,
    pub description: String,
}

impl __sdk::InModule for Dnd5ELanguage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ELanguage`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ELanguageCols {
    pub id: __sdk::__query_builder::Col<Dnd5ELanguage, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5ELanguage, String>,
    pub name: __sdk::__query_builder::Col<Dnd5ELanguage, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ELanguage, String>,
    pub kind: __sdk::__query_builder::Col<Dnd5ELanguage, Option<String>>,
    pub script: __sdk::__query_builder::Col<Dnd5ELanguage, Option<String>>,
    pub origin: __sdk::__query_builder::Col<Dnd5ELanguage, Option<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5ELanguage, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ELanguage {
    type Cols = Dnd5ELanguageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ELanguageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            script: __sdk::__query_builder::Col::new(table_name, "script"),
            origin: __sdk::__query_builder::Col::new(table_name, "origin"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ELanguage`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ELanguageIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ELanguage, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5ELanguage, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ELanguage {
    type IxCols = Dnd5ELanguageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ELanguageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ELanguage {}
