// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ESense {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub description: String,
}

impl __sdk::InModule for Dnd5ESense {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ESense`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ESenseCols {
    pub id: __sdk::__query_builder::Col<Dnd5ESense, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5ESense, String>,
    pub name: __sdk::__query_builder::Col<Dnd5ESense, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ESense, String>,
    pub description: __sdk::__query_builder::Col<Dnd5ESense, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ESense {
    type Cols = Dnd5ESenseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ESenseCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ESense`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ESenseIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ESense, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5ESense, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ESense {
    type IxCols = Dnd5ESenseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ESenseIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ESense {}
