// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_condition_type::Dnd5ECondition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_condition`.
///
/// Obtain a handle from the [`Dnd5EConditionTableAccess::dnd_5_e_condition`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_condition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_condition().on_insert(...)`.
pub struct Dnd5EConditionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5ECondition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_condition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EConditionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EConditionTableHandle`], which mediates access to the table `dnd_5_e_condition`.
    fn dnd_5_e_condition(&self) -> Dnd5EConditionTableHandle<'_>;
}

impl Dnd5EConditionTableAccess for super::RemoteTables {
    fn dnd_5_e_condition(&self) -> Dnd5EConditionTableHandle<'_> {
        Dnd5EConditionTableHandle {
            imp: self.imp.get_table::<Dnd5ECondition>("dnd_5_e_condition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EConditionInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EConditionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EConditionTableHandle<'ctx> {
    type Row = Dnd5ECondition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5ECondition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EConditionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EConditionInsertCallbackId {
        Dnd5EConditionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EConditionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EConditionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EConditionDeleteCallbackId {
        Dnd5EConditionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EConditionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EConditionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EConditionTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EConditionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EConditionUpdateCallbackId {
        Dnd5EConditionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EConditionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_condition`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EConditionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_condition().id().find(...)`.
pub struct Dnd5EConditionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ECondition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EConditionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_condition`.
    pub fn id(&self) -> Dnd5EConditionIdUnique<'ctx> {
        Dnd5EConditionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EConditionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5ECondition> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_condition`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EConditionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_condition().key().find(...)`.
pub struct Dnd5EConditionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5ECondition, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EConditionTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_condition`.
    pub fn key(&self) -> Dnd5EConditionKeyUnique<'ctx> {
        Dnd5EConditionKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EConditionKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5ECondition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5ECondition>("dnd_5_e_condition");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5ECondition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5ECondition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5ECondition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_conditionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5ECondition`.
    fn dnd_5_e_condition(&self) -> __sdk::__query_builder::Table<Dnd5ECondition>;
}

impl dnd_5_e_conditionQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_condition(&self) -> __sdk::__query_builder::Table<Dnd5ECondition> {
        __sdk::__query_builder::Table::new("dnd_5_e_condition")
    }
}
