// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ECondition {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub description: String,
}

impl __sdk::InModule for Dnd5ECondition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ECondition`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EConditionCols {
    pub id: __sdk::__query_builder::Col<Dnd5ECondition, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5ECondition, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ECondition, String>,
    pub description: __sdk::__query_builder::Col<Dnd5ECondition, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ECondition {
    type Cols = Dnd5EConditionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EConditionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ECondition`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EConditionIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ECondition, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ECondition {
    type IxCols = Dnd5EConditionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EConditionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ECondition {}
