// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_deity_type::Dnd5EDeity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_deity`.
///
/// Obtain a handle from the [`Dnd5EDeityTableAccess::dnd_5_e_deity`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_deity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_deity().on_insert(...)`.
pub struct Dnd5EDeityTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EDeity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_deity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EDeityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EDeityTableHandle`], which mediates access to the table `dnd_5_e_deity`.
    fn dnd_5_e_deity(&self) -> Dnd5EDeityTableHandle<'_>;
}

impl Dnd5EDeityTableAccess for super::RemoteTables {
    fn dnd_5_e_deity(&self) -> Dnd5EDeityTableHandle<'_> {
        Dnd5EDeityTableHandle {
            imp: self.imp.get_table::<Dnd5EDeity>("dnd_5_e_deity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EDeityInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EDeityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EDeityTableHandle<'ctx> {
    type Row = Dnd5EDeity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EDeity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EDeityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeityInsertCallbackId {
        Dnd5EDeityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EDeityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EDeityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeityDeleteCallbackId {
        Dnd5EDeityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EDeityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EDeityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EDeityTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EDeityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EDeityUpdateCallbackId {
        Dnd5EDeityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EDeityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_deity`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EDeityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_deity().id().find(...)`.
pub struct Dnd5EDeityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EDeity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EDeityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_deity`.
    pub fn id(&self) -> Dnd5EDeityIdUnique<'ctx> {
        Dnd5EDeityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EDeityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EDeity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EDeity>("dnd_5_e_deity");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EDeity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EDeity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EDeity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_deityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EDeity`.
    fn dnd_5_e_deity(&self) -> __sdk::__query_builder::Table<Dnd5EDeity>;
}

impl dnd_5_e_deityQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_deity(&self) -> __sdk::__query_builder::Table<Dnd5EDeity> {
        __sdk::__query_builder::Table::new("dnd_5_e_deity")
    }
}
