// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_action_type::Dnd5EAction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_action`.
///
/// Obtain a handle from the [`Dnd5EActionTableAccess::dnd_5_e_action`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_action()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_action().on_insert(...)`.
pub struct Dnd5EActionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EAction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_action`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EActionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EActionTableHandle`], which mediates access to the table `dnd_5_e_action`.
    fn dnd_5_e_action(&self) -> Dnd5EActionTableHandle<'_>;
}

impl Dnd5EActionTableAccess for super::RemoteTables {
    fn dnd_5_e_action(&self) -> Dnd5EActionTableHandle<'_> {
        Dnd5EActionTableHandle {
            imp: self.imp.get_table::<Dnd5EAction>("dnd_5_e_action"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EActionInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EActionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EActionTableHandle<'ctx> {
    type Row = Dnd5EAction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EAction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EActionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EActionInsertCallbackId {
        Dnd5EActionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EActionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EActionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EActionDeleteCallbackId {
        Dnd5EActionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EActionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EActionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EActionTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EActionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EActionUpdateCallbackId {
        Dnd5EActionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EActionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_action`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EActionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_action().id().find(...)`.
pub struct Dnd5EActionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EAction, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EActionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_action`.
    pub fn id(&self) -> Dnd5EActionIdUnique<'ctx> {
        Dnd5EActionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EActionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EAction> {
        self.imp.find(col_val)
    }
}

/// Access to the `key` unique index on the table `dnd_5_e_action`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EActionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_action().key().find(...)`.
pub struct Dnd5EActionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EAction, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EActionTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `dnd_5_e_action`.
    pub fn key(&self) -> Dnd5EActionKeyUnique<'ctx> {
        Dnd5EActionKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EActionKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Dnd5EAction> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EAction>("dnd_5_e_action");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EAction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EAction>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EAction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_actionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EAction`.
    fn dnd_5_e_action(&self) -> __sdk::__query_builder::Table<Dnd5EAction>;
}

impl dnd_5_e_actionQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_action(&self) -> __sdk::__query_builder::Table<Dnd5EAction> {
        __sdk::__query_builder::Table::new("dnd_5_e_action")
    }
}
