// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_background_type::Dnd5EBackground;
use super::language_grant_type::LanguageGrant;
use super::skill_grant_type::SkillGrant;
use super::tool_grant_type::ToolGrant;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_background`.
///
/// Obtain a handle from the [`Dnd5EBackgroundTableAccess::dnd_5_e_background`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_background()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_background().on_insert(...)`.
pub struct Dnd5EBackgroundTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EBackground>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_background`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EBackgroundTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EBackgroundTableHandle`], which mediates access to the table `dnd_5_e_background`.
    fn dnd_5_e_background(&self) -> Dnd5EBackgroundTableHandle<'_>;
}

impl Dnd5EBackgroundTableAccess for super::RemoteTables {
    fn dnd_5_e_background(&self) -> Dnd5EBackgroundTableHandle<'_> {
        Dnd5EBackgroundTableHandle {
            imp: self.imp.get_table::<Dnd5EBackground>("dnd_5_e_background"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EBackgroundInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EBackgroundDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EBackgroundTableHandle<'ctx> {
    type Row = Dnd5EBackground;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EBackground> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EBackgroundInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EBackgroundInsertCallbackId {
        Dnd5EBackgroundInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EBackgroundInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EBackgroundDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EBackgroundDeleteCallbackId {
        Dnd5EBackgroundDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EBackgroundDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EBackgroundUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EBackgroundTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EBackgroundUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EBackgroundUpdateCallbackId {
        Dnd5EBackgroundUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EBackgroundUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_background`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EBackgroundIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_background().id().find(...)`.
pub struct Dnd5EBackgroundIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EBackground, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EBackgroundTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_background`.
    pub fn id(&self) -> Dnd5EBackgroundIdUnique<'ctx> {
        Dnd5EBackgroundIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EBackgroundIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EBackground> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EBackground>("dnd_5_e_background");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EBackground>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EBackground>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EBackground`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_backgroundQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EBackground`.
    fn dnd_5_e_background(&self) -> __sdk::__query_builder::Table<Dnd5EBackground>;
}

impl dnd_5_e_backgroundQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_background(&self) -> __sdk::__query_builder::Table<Dnd5EBackground> {
        __sdk::__query_builder::Table::new("dnd_5_e_background")
    }
}
