// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EVehicle {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub vehicle_type: String,
    pub size: Vec<String>,
    pub terrain: Vec<String>,
    pub crew_capacity: Option<u16>,
    pub passenger_capacity: Option<u16>,
    pub pace: Option<u16>,
    pub ac: Option<u16>,
    pub hp: Option<u16>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EVehicle {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EVehicle`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EVehicleCols {
    pub id: __sdk::__query_builder::Col<Dnd5EVehicle, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EVehicle, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EVehicle, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EVehicle, String>,
    pub vehicle_type: __sdk::__query_builder::Col<Dnd5EVehicle, String>,
    pub size: __sdk::__query_builder::Col<Dnd5EVehicle, Vec<String>>,
    pub terrain: __sdk::__query_builder::Col<Dnd5EVehicle, Vec<String>>,
    pub crew_capacity: __sdk::__query_builder::Col<Dnd5EVehicle, Option<u16>>,
    pub passenger_capacity: __sdk::__query_builder::Col<Dnd5EVehicle, Option<u16>>,
    pub pace: __sdk::__query_builder::Col<Dnd5EVehicle, Option<u16>>,
    pub ac: __sdk::__query_builder::Col<Dnd5EVehicle, Option<u16>>,
    pub hp: __sdk::__query_builder::Col<Dnd5EVehicle, Option<u16>>,
    pub description: __sdk::__query_builder::Col<Dnd5EVehicle, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EVehicle {
    type Cols = Dnd5EVehicleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EVehicleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            vehicle_type: __sdk::__query_builder::Col::new(table_name, "vehicle_type"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            terrain: __sdk::__query_builder::Col::new(table_name, "terrain"),
            crew_capacity: __sdk::__query_builder::Col::new(table_name, "crew_capacity"),
            passenger_capacity: __sdk::__query_builder::Col::new(table_name, "passenger_capacity"),
            pace: __sdk::__query_builder::Col::new(table_name, "pace"),
            ac: __sdk::__query_builder::Col::new(table_name, "ac"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EVehicle`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EVehicleIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EVehicle, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EVehicle, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EVehicle {
    type IxCols = Dnd5EVehicleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EVehicleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EVehicle {}
