// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_rarity_type::ItemRarity;
use super::item_type_type::ItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EItem {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub item_type: ItemType,
    pub rarity: ItemRarity,
    pub weight: Option<f32>,
    pub value_cp: Option<u32>,
    pub wondrous: bool,
    pub attunement: Option<String>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EItem`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EItemCols {
    pub id: __sdk::__query_builder::Col<Dnd5EItem, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5EItem, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EItem, String>,
    pub item_type: __sdk::__query_builder::Col<Dnd5EItem, ItemType>,
    pub rarity: __sdk::__query_builder::Col<Dnd5EItem, ItemRarity>,
    pub weight: __sdk::__query_builder::Col<Dnd5EItem, Option<f32>>,
    pub value_cp: __sdk::__query_builder::Col<Dnd5EItem, Option<u32>>,
    pub wondrous: __sdk::__query_builder::Col<Dnd5EItem, bool>,
    pub attunement: __sdk::__query_builder::Col<Dnd5EItem, Option<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5EItem, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EItem {
    type Cols = Dnd5EItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            item_type: __sdk::__query_builder::Col::new(table_name, "item_type"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            value_cp: __sdk::__query_builder::Col::new(table_name, "value_cp"),
            wondrous: __sdk::__query_builder::Col::new(table_name, "wondrous"),
            attunement: __sdk::__query_builder::Col::new(table_name, "attunement"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EItemIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EItem, u64>,
    pub item_type: __sdk::__query_builder::IxCol<Dnd5EItem, ItemType>,
    pub rarity: __sdk::__query_builder::IxCol<Dnd5EItem, ItemRarity>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EItem {
    type IxCols = Dnd5EItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            item_type: __sdk::__query_builder::IxCol::new(table_name, "item_type"),
            rarity: __sdk::__query_builder::IxCol::new(table_name, "rarity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EItem {}
