// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::feat_category_type::FeatCategory;
use super::feat_prereq_type::FeatPrereq;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EFeat {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub category: Option<FeatCategory>,
    pub prerequisite: Option<FeatPrereq>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EFeat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EFeat`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EFeatCols {
    pub id: __sdk::__query_builder::Col<Dnd5EFeat, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EFeat, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EFeat, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EFeat, String>,
    pub category: __sdk::__query_builder::Col<Dnd5EFeat, Option<FeatCategory>>,
    pub prerequisite: __sdk::__query_builder::Col<Dnd5EFeat, Option<FeatPrereq>>,
    pub description: __sdk::__query_builder::Col<Dnd5EFeat, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EFeat {
    type Cols = Dnd5EFeatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EFeatCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            prerequisite: __sdk::__query_builder::Col::new(table_name, "prerequisite"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EFeat`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EFeatIxCols {
    pub category: __sdk::__query_builder::IxCol<Dnd5EFeat, Option<FeatCategory>>,
    pub id: __sdk::__query_builder::IxCol<Dnd5EFeat, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EFeat, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EFeat {
    type IxCols = Dnd5EFeatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EFeatIxCols {
            category: __sdk::__query_builder::IxCol::new(table_name, "category"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EFeat {}
