// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EDeck {
    pub id: u64,
    pub name: String,
    pub source: String,
    pub cards: Vec<String>,
    pub description: String,
}

impl __sdk::InModule for Dnd5EDeck {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EDeck`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EDeckCols {
    pub id: __sdk::__query_builder::Col<Dnd5EDeck, u64>,
    pub name: __sdk::__query_builder::Col<Dnd5EDeck, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EDeck, String>,
    pub cards: __sdk::__query_builder::Col<Dnd5EDeck, Vec<String>>,
    pub description: __sdk::__query_builder::Col<Dnd5EDeck, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EDeck {
    type Cols = Dnd5EDeckCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EDeckCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            cards: __sdk::__query_builder::Col::new(table_name, "cards"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EDeck`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EDeckIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EDeck, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EDeck {
    type IxCols = Dnd5EDeckIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EDeckIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EDeck {}
