// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dnd_5_e_psionic_type::Dnd5EPsionic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dnd_5_e_psionic`.
///
/// Obtain a handle from the [`Dnd5EPsionicTableAccess::dnd_5_e_psionic`] method on [`super::RemoteTables`],
/// like `ctx.db.dnd_5_e_psionic()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_psionic().on_insert(...)`.
pub struct Dnd5EPsionicTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dnd5EPsionic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dnd_5_e_psionic`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Dnd5EPsionicTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Dnd5EPsionicTableHandle`], which mediates access to the table `dnd_5_e_psionic`.
    fn dnd_5_e_psionic(&self) -> Dnd5EPsionicTableHandle<'_>;
}

impl Dnd5EPsionicTableAccess for super::RemoteTables {
    fn dnd_5_e_psionic(&self) -> Dnd5EPsionicTableHandle<'_> {
        Dnd5EPsionicTableHandle {
            imp: self.imp.get_table::<Dnd5EPsionic>("dnd_5_e_psionic"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Dnd5EPsionicInsertCallbackId(__sdk::CallbackId);
pub struct Dnd5EPsionicDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Dnd5EPsionicTableHandle<'ctx> {
    type Row = Dnd5EPsionic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dnd5EPsionic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Dnd5EPsionicInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EPsionicInsertCallbackId {
        Dnd5EPsionicInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Dnd5EPsionicInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Dnd5EPsionicDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Dnd5EPsionicDeleteCallbackId {
        Dnd5EPsionicDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Dnd5EPsionicDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct Dnd5EPsionicUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Dnd5EPsionicTableHandle<'ctx> {
    type UpdateCallbackId = Dnd5EPsionicUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Dnd5EPsionicUpdateCallbackId {
        Dnd5EPsionicUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Dnd5EPsionicUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dnd_5_e_psionic`,
/// which allows point queries on the field of the same name
/// via the [`Dnd5EPsionicIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dnd_5_e_psionic().id().find(...)`.
pub struct Dnd5EPsionicIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dnd5EPsionic, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Dnd5EPsionicTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dnd_5_e_psionic`.
    pub fn id(&self) -> Dnd5EPsionicIdUnique<'ctx> {
        Dnd5EPsionicIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Dnd5EPsionicIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Dnd5EPsionic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dnd5EPsionic>("dnd_5_e_psionic");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dnd5EPsionic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dnd5EPsionic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dnd5EPsionic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dnd_5_e_psionicQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dnd5EPsionic`.
    fn dnd_5_e_psionic(&self) -> __sdk::__query_builder::Table<Dnd5EPsionic>;
}

impl dnd_5_e_psionicQueryTableAccess for __sdk::QueryTableAccessor {
    fn dnd_5_e_psionic(&self) -> __sdk::__query_builder::Table<Dnd5EPsionic> {
        __sdk::__query_builder::Table::new("dnd_5_e_psionic")
    }
}
