// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5ETrapHazard {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub kind: String,
    pub trap_hazard_type: Option<String>,
    pub trigger: String,
    pub effect: String,
    pub countermeasures: String,
    pub description: String,
}

impl __sdk::InModule for Dnd5ETrapHazard {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5ETrapHazard`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5ETrapHazardCols {
    pub id: __sdk::__query_builder::Col<Dnd5ETrapHazard, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub name: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub source: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub kind: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub trap_hazard_type: __sdk::__query_builder::Col<Dnd5ETrapHazard, Option<String>>,
    pub trigger: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub effect: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub countermeasures: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
    pub description: __sdk::__query_builder::Col<Dnd5ETrapHazard, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5ETrapHazard {
    type Cols = Dnd5ETrapHazardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5ETrapHazardCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            trap_hazard_type: __sdk::__query_builder::Col::new(table_name, "trap_hazard_type"),
            trigger: __sdk::__query_builder::Col::new(table_name, "trigger"),
            effect: __sdk::__query_builder::Col::new(table_name, "effect"),
            countermeasures: __sdk::__query_builder::Col::new(table_name, "countermeasures"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5ETrapHazard`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5ETrapHazardIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5ETrapHazard, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5ETrapHazard, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5ETrapHazard {
    type IxCols = Dnd5ETrapHazardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5ETrapHazardIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5ETrapHazard {}
