// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dnd5EClassFeature {
    pub id: u64,
    pub key: String,
    pub name: String,
    pub source: String,
    pub class_name: String,
    pub class_source: String,
    pub level: u8,
    pub description: String,
}

impl __sdk::InModule for Dnd5EClassFeature {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dnd5EClassFeature`.
///
/// Provides typed access to columns for query building.
pub struct Dnd5EClassFeatureCols {
    pub id: __sdk::__query_builder::Col<Dnd5EClassFeature, u64>,
    pub key: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
    pub name: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
    pub source: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
    pub class_name: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
    pub class_source: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
    pub level: __sdk::__query_builder::Col<Dnd5EClassFeature, u8>,
    pub description: __sdk::__query_builder::Col<Dnd5EClassFeature, String>,
}

impl __sdk::__query_builder::HasCols for Dnd5EClassFeature {
    type Cols = Dnd5EClassFeatureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        Dnd5EClassFeatureCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            class_name: __sdk::__query_builder::Col::new(table_name, "class_name"),
            class_source: __sdk::__query_builder::Col::new(table_name, "class_source"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `Dnd5EClassFeature`.
///
/// Provides typed access to indexed columns for query building.
pub struct Dnd5EClassFeatureIxCols {
    pub id: __sdk::__query_builder::IxCol<Dnd5EClassFeature, u64>,
    pub key: __sdk::__query_builder::IxCol<Dnd5EClassFeature, String>,
}

impl __sdk::__query_builder::HasIxCols for Dnd5EClassFeature {
    type IxCols = Dnd5EClassFeatureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        Dnd5EClassFeatureIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dnd5EClassFeature {}
