// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_score_type::AbilityScore;
use super::race_type::Race;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FeatPrereq {
    pub level: Option<u8>,
    pub races: Vec<Race>,
    pub abilities: Vec<AbilityScore>,
    pub spellcasting: bool,
}

impl __sdk::InModule for FeatPrereq {
    type Module = super::RemoteModule;
}
