// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::language_choice_type::LanguageChoice;
use super::language_type::Language;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum LanguageGrant {
    Fixed(Vec<Language>),

    Choose(LanguageChoice),

    AnyStandard(u8),

    AnyExotic(u8),

    Any(u8),
}

impl __sdk::InModule for LanguageGrant {
    type Module = super::RemoteModule;
}
