// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit f3109bbaa05d2de4d801394058adca36903d4259).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ability_bonus_type;
pub mod ability_choice_type;
pub mod ability_grant_type;
pub mod ability_score_type;
pub mod ability_type;
pub mod alignment_type;
pub mod caster_progression_type;
pub mod class_level_prereq_type;
pub mod class_type;
pub mod creature_size_type;
pub mod creature_type_type;
pub mod dnd_5_e_action_table;
pub mod dnd_5_e_action_type;
pub mod dnd_5_e_background_table;
pub mod dnd_5_e_background_type;
pub mod dnd_5_e_char_creation_option_table;
pub mod dnd_5_e_char_creation_option_type;
pub mod dnd_5_e_class_feature_table;
pub mod dnd_5_e_class_feature_type;
pub mod dnd_5_e_class_table;
pub mod dnd_5_e_class_type;
pub mod dnd_5_e_condition_table;
pub mod dnd_5_e_condition_type;
pub mod dnd_5_e_cult_boon_table;
pub mod dnd_5_e_cult_boon_type;
pub mod dnd_5_e_deck_table;
pub mod dnd_5_e_deck_type;
pub mod dnd_5_e_deity_table;
pub mod dnd_5_e_deity_type;
pub mod dnd_5_e_feat_table;
pub mod dnd_5_e_feat_type;
pub mod dnd_5_e_item_table;
pub mod dnd_5_e_item_type;
pub mod dnd_5_e_language_table;
pub mod dnd_5_e_language_type;
pub mod dnd_5_e_monster_table;
pub mod dnd_5_e_monster_type;
pub mod dnd_5_e_object_table;
pub mod dnd_5_e_object_type;
pub mod dnd_5_e_optional_feature_table;
pub mod dnd_5_e_optional_feature_type;
pub mod dnd_5_e_psionic_table;
pub mod dnd_5_e_psionic_type;
pub mod dnd_5_e_race_table;
pub mod dnd_5_e_race_type;
pub mod dnd_5_e_recipe_table;
pub mod dnd_5_e_recipe_type;
pub mod dnd_5_e_reward_table;
pub mod dnd_5_e_reward_type;
pub mod dnd_5_e_sense_table;
pub mod dnd_5_e_sense_type;
pub mod dnd_5_e_skill_table;
pub mod dnd_5_e_skill_type;
pub mod dnd_5_e_spell_table;
pub mod dnd_5_e_spell_type;
pub mod dnd_5_e_subclass_feature_table;
pub mod dnd_5_e_subclass_feature_type;
pub mod dnd_5_e_subclass_table;
pub mod dnd_5_e_subclass_type;
pub mod dnd_5_e_trap_hazard_table;
pub mod dnd_5_e_trap_hazard_type;
pub mod dnd_5_e_variant_rule_table;
pub mod dnd_5_e_variant_rule_type;
pub mod dnd_5_e_vehicle_table;
pub mod dnd_5_e_vehicle_type;
pub mod feat_category_type;
pub mod feat_prereq_type;
pub mod item_rarity_type;
pub mod item_type_type;
pub mod language_choice_type;
pub mod language_grant_type;
pub mod language_type;
pub mod message_table;
pub mod message_type;
pub mod optional_feature_prereq_type;
pub mod optional_feature_type_type;
pub mod pact_boon_type;
pub mod race_type;
pub mod seed_dnd_5_e_action_reducer;
pub mod seed_dnd_5_e_background_reducer;
pub mod seed_dnd_5_e_char_creation_option_reducer;
pub mod seed_dnd_5_e_class_feature_reducer;
pub mod seed_dnd_5_e_class_reducer;
pub mod seed_dnd_5_e_condition_reducer;
pub mod seed_dnd_5_e_cult_boon_reducer;
pub mod seed_dnd_5_e_deck_reducer;
pub mod seed_dnd_5_e_deity_reducer;
pub mod seed_dnd_5_e_feat_reducer;
pub mod seed_dnd_5_e_item_reducer;
pub mod seed_dnd_5_e_language_reducer;
pub mod seed_dnd_5_e_monster_reducer;
pub mod seed_dnd_5_e_object_reducer;
pub mod seed_dnd_5_e_optional_feature_reducer;
pub mod seed_dnd_5_e_psionic_reducer;
pub mod seed_dnd_5_e_race_reducer;
pub mod seed_dnd_5_e_recipe_reducer;
pub mod seed_dnd_5_e_reward_reducer;
pub mod seed_dnd_5_e_sense_reducer;
pub mod seed_dnd_5_e_skill_reducer;
pub mod seed_dnd_5_e_spell_reducer;
pub mod seed_dnd_5_e_subclass_feature_reducer;
pub mod seed_dnd_5_e_subclass_reducer;
pub mod seed_dnd_5_e_trap_hazard_reducer;
pub mod seed_dnd_5_e_variant_rule_reducer;
pub mod seed_dnd_5_e_vehicle_reducer;
pub mod send_message_reducer;
pub mod set_name_reducer;
pub mod skill_choice_type;
pub mod skill_grant_type;
pub mod skill_type;
pub mod speed_type;
pub mod spell_school_type;
pub mod string_choice_type;
pub mod tool_grant_type;
pub mod user_table;
pub mod user_type;
pub mod warlock_patron_type;

pub use ability_bonus_type::AbilityBonus;
pub use ability_choice_type::AbilityChoice;
pub use ability_grant_type::AbilityGrant;
pub use ability_score_type::AbilityScore;
pub use ability_type::Ability;
pub use alignment_type::Alignment;
pub use caster_progression_type::CasterProgression;
pub use class_level_prereq_type::ClassLevelPrereq;
pub use class_type::Class;
pub use creature_size_type::CreatureSize;
pub use creature_type_type::CreatureType;
pub use dnd_5_e_action_table::*;
pub use dnd_5_e_action_type::Dnd5EAction;
pub use dnd_5_e_background_table::*;
pub use dnd_5_e_background_type::Dnd5EBackground;
pub use dnd_5_e_char_creation_option_table::*;
pub use dnd_5_e_char_creation_option_type::Dnd5ECharCreationOption;
pub use dnd_5_e_class_feature_table::*;
pub use dnd_5_e_class_feature_type::Dnd5EClassFeature;
pub use dnd_5_e_class_table::*;
pub use dnd_5_e_class_type::Dnd5EClass;
pub use dnd_5_e_condition_table::*;
pub use dnd_5_e_condition_type::Dnd5ECondition;
pub use dnd_5_e_cult_boon_table::*;
pub use dnd_5_e_cult_boon_type::Dnd5ECultBoon;
pub use dnd_5_e_deck_table::*;
pub use dnd_5_e_deck_type::Dnd5EDeck;
pub use dnd_5_e_deity_table::*;
pub use dnd_5_e_deity_type::Dnd5EDeity;
pub use dnd_5_e_feat_table::*;
pub use dnd_5_e_feat_type::Dnd5EFeat;
pub use dnd_5_e_item_table::*;
pub use dnd_5_e_item_type::Dnd5EItem;
pub use dnd_5_e_language_table::*;
pub use dnd_5_e_language_type::Dnd5ELanguage;
pub use dnd_5_e_monster_table::*;
pub use dnd_5_e_monster_type::Dnd5EMonster;
pub use dnd_5_e_object_table::*;
pub use dnd_5_e_object_type::Dnd5EObject;
pub use dnd_5_e_optional_feature_table::*;
pub use dnd_5_e_optional_feature_type::Dnd5EOptionalFeature;
pub use dnd_5_e_psionic_table::*;
pub use dnd_5_e_psionic_type::Dnd5EPsionic;
pub use dnd_5_e_race_table::*;
pub use dnd_5_e_race_type::Dnd5ERace;
pub use dnd_5_e_recipe_table::*;
pub use dnd_5_e_recipe_type::Dnd5ERecipe;
pub use dnd_5_e_reward_table::*;
pub use dnd_5_e_reward_type::Dnd5EReward;
pub use dnd_5_e_sense_table::*;
pub use dnd_5_e_sense_type::Dnd5ESense;
pub use dnd_5_e_skill_table::*;
pub use dnd_5_e_skill_type::Dnd5ESkill;
pub use dnd_5_e_spell_table::*;
pub use dnd_5_e_spell_type::Dnd5ESpell;
pub use dnd_5_e_subclass_feature_table::*;
pub use dnd_5_e_subclass_feature_type::Dnd5ESubclassFeature;
pub use dnd_5_e_subclass_table::*;
pub use dnd_5_e_subclass_type::Dnd5ESubclass;
pub use dnd_5_e_trap_hazard_table::*;
pub use dnd_5_e_trap_hazard_type::Dnd5ETrapHazard;
pub use dnd_5_e_variant_rule_table::*;
pub use dnd_5_e_variant_rule_type::Dnd5EVariantRule;
pub use dnd_5_e_vehicle_table::*;
pub use dnd_5_e_vehicle_type::Dnd5EVehicle;
pub use feat_category_type::FeatCategory;
pub use feat_prereq_type::FeatPrereq;
pub use item_rarity_type::ItemRarity;
pub use item_type_type::ItemType;
pub use language_choice_type::LanguageChoice;
pub use language_grant_type::LanguageGrant;
pub use language_type::Language;
pub use message_table::*;
pub use message_type::Message;
pub use optional_feature_prereq_type::OptionalFeaturePrereq;
pub use optional_feature_type_type::OptionalFeatureType;
pub use pact_boon_type::PactBoon;
pub use race_type::Race;
pub use seed_dnd_5_e_action_reducer::seed_dnd_5_e_action;
pub use seed_dnd_5_e_background_reducer::seed_dnd_5_e_background;
pub use seed_dnd_5_e_char_creation_option_reducer::seed_dnd_5_e_char_creation_option;
pub use seed_dnd_5_e_class_feature_reducer::seed_dnd_5_e_class_feature;
pub use seed_dnd_5_e_class_reducer::seed_dnd_5_e_class;
pub use seed_dnd_5_e_condition_reducer::seed_dnd_5_e_condition;
pub use seed_dnd_5_e_cult_boon_reducer::seed_dnd_5_e_cult_boon;
pub use seed_dnd_5_e_deck_reducer::seed_dnd_5_e_deck;
pub use seed_dnd_5_e_deity_reducer::seed_dnd_5_e_deity;
pub use seed_dnd_5_e_feat_reducer::seed_dnd_5_e_feat;
pub use seed_dnd_5_e_item_reducer::seed_dnd_5_e_item;
pub use seed_dnd_5_e_language_reducer::seed_dnd_5_e_language;
pub use seed_dnd_5_e_monster_reducer::seed_dnd_5_e_monster;
pub use seed_dnd_5_e_object_reducer::seed_dnd_5_e_object;
pub use seed_dnd_5_e_optional_feature_reducer::seed_dnd_5_e_optional_feature;
pub use seed_dnd_5_e_psionic_reducer::seed_dnd_5_e_psionic;
pub use seed_dnd_5_e_race_reducer::seed_dnd_5_e_race;
pub use seed_dnd_5_e_recipe_reducer::seed_dnd_5_e_recipe;
pub use seed_dnd_5_e_reward_reducer::seed_dnd_5_e_reward;
pub use seed_dnd_5_e_sense_reducer::seed_dnd_5_e_sense;
pub use seed_dnd_5_e_skill_reducer::seed_dnd_5_e_skill;
pub use seed_dnd_5_e_spell_reducer::seed_dnd_5_e_spell;
pub use seed_dnd_5_e_subclass_feature_reducer::seed_dnd_5_e_subclass_feature;
pub use seed_dnd_5_e_subclass_reducer::seed_dnd_5_e_subclass;
pub use seed_dnd_5_e_trap_hazard_reducer::seed_dnd_5_e_trap_hazard;
pub use seed_dnd_5_e_variant_rule_reducer::seed_dnd_5_e_variant_rule;
pub use seed_dnd_5_e_vehicle_reducer::seed_dnd_5_e_vehicle;
pub use send_message_reducer::send_message;
pub use set_name_reducer::set_name;
pub use skill_choice_type::SkillChoice;
pub use skill_grant_type::SkillGrant;
pub use skill_type::Skill;
pub use speed_type::Speed;
pub use spell_school_type::SpellSchool;
pub use string_choice_type::StringChoice;
pub use tool_grant_type::ToolGrant;
pub use user_table::*;
pub use user_type::User;
pub use warlock_patron_type::WarlockPatron;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    SeedDnd5EAction {
        name: String,
        source: String,
        time: String,
        description: String,
    },
    SeedDnd5EBackground {
        name: String,
        source: String,
        skill_proficiencies: Vec<SkillGrant>,
        tool_proficiencies: Vec<ToolGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    },
    SeedDnd5ECharCreationOption {
        name: String,
        source: String,
        option_types: Vec<String>,
        description: String,
    },
    SeedDnd5EClass {
        name: String,
        source: String,
        edition: Option<String>,
        hit_die: u8,
        saving_throws: Vec<Ability>,
        spellcasting_ability: Option<Ability>,
        caster_progression: Option<CasterProgression>,
        prepared_spells_formula: Option<String>,
        prepared_spells_progression: Vec<u8>,
        cantrip_progression: Vec<u8>,
        class_features: Vec<String>,
        subclass_title: Option<String>,
    },
    SeedDnd5EClassFeature {
        name: String,
        source: String,
        class_name: String,
        class_source: String,
        level: u8,
        description: String,
    },
    SeedDnd5ECondition {
        name: String,
        source: String,
        description: String,
    },
    SeedDnd5ECultBoon {
        name: String,
        source: String,
        kind: String,
        subtype: Option<String>,
        goal: Option<String>,
        cultists: Option<String>,
        signature_spells: Option<String>,
        ability_text: Option<String>,
        description: String,
    },
    SeedDnd5EDeck {
        name: String,
        source: String,
        cards: Vec<String>,
        description: String,
    },
    SeedDnd5EDeity {
        name: String,
        source: String,
        pantheon: Option<String>,
        alignment: Vec<Alignment>,
        category: Option<String>,
        domains: Vec<String>,
        province: Option<String>,
        title: Option<String>,
        symbol: Option<String>,
        description: String,
    },
    SeedDnd5EFeat {
        name: String,
        source: String,
        category: Option<FeatCategory>,
        prerequisite: Option<FeatPrereq>,
        description: String,
    },
    SeedDnd5EItem {
        name: String,
        source: String,
        item_type: ItemType,
        rarity: ItemRarity,
        weight: Option<f32>,
        value_cp: Option<u32>,
        wondrous: bool,
        attunement: Option<String>,
        description: String,
    },
    SeedDnd5ELanguage {
        name: String,
        source: String,
        kind: Option<String>,
        script: Option<String>,
        origin: Option<String>,
        description: String,
    },
    SeedDnd5EMonster {
        name: String,
        source: String,
        size: CreatureSize,
        creature_type: CreatureType,
        cr: String,
        ac: u8,
        hp_average: u16,
        hp_formula: String,
        speed_walk: u16,
        speed_fly: u16,
        speed_swim: u16,
        str_score: u8,
        dex_score: u8,
        con_score: u8,
        int_score: u8,
        wis_score: u8,
        cha_score: u8,
        description: String,
    },
    SeedDnd5EObject {
        name: String,
        source: String,
        size: Vec<CreatureSize>,
        object_type: Option<String>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
        action_description: String,
    },
    SeedDnd5EOptionalFeature {
        name: String,
        source: String,
        feature_types: Vec<OptionalFeatureType>,
        prerequisite: Option<OptionalFeaturePrereq>,
        description: String,
    },
    SeedDnd5EPsionic {
        name: String,
        source: String,
        kind: String,
        order_name: Option<String>,
        focus: Option<String>,
        description: String,
        modes: String,
    },
    SeedDnd5ERace {
        name: String,
        source: String,
        size: CreatureSize,
        speed: Speed,
        ability_bonuses: Vec<AbilityGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    },
    SeedDnd5ERecipe {
        name: String,
        source: String,
        recipe_type: Option<String>,
        dish_types: Vec<String>,
        diet: Option<String>,
        serves: Option<String>,
        ingredients: String,
        instructions: String,
    },
    SeedDnd5EReward {
        name: String,
        source: String,
        reward_type: Option<String>,
        description: String,
    },
    SeedDnd5ESense {
        name: String,
        source: String,
        description: String,
    },
    SeedDnd5ESkill {
        name: String,
        source: String,
        ability: Ability,
        description: String,
    },
    SeedDnd5ESpell {
        name: String,
        source: String,
        level: u8,
        school: SpellSchool,
        ritual: bool,
        concentration: bool,
        description: String,
        saving_throw: Option<Ability>,
    },
    SeedDnd5ESubclass {
        name: String,
        short_name: String,
        source: String,
        class_name: String,
        class_source: String,
        edition: Option<String>,
        spellcasting_ability: Option<Ability>,
        caster_progression: Option<CasterProgression>,
        cantrip_progression: Vec<u8>,
        subclass_features: Vec<String>,
    },
    SeedDnd5ESubclassFeature {
        name: String,
        source: String,
        class_name: String,
        class_source: String,
        subclass_short_name: String,
        subclass_source: String,
        level: u8,
        description: String,
    },
    SeedDnd5ETrapHazard {
        name: String,
        source: String,
        kind: String,
        trap_hazard_type: Option<String>,
        trigger: String,
        effect: String,
        countermeasures: String,
        description: String,
    },
    SeedDnd5EVariantRule {
        name: String,
        source: String,
        rule_type: Option<String>,
        description: String,
    },
    SeedDnd5EVehicle {
        name: String,
        source: String,
        vehicle_type: String,
        size: Vec<String>,
        terrain: Vec<String>,
        crew_capacity: Option<u16>,
        passenger_capacity: Option<u16>,
        pace: Option<u16>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
    },
    SendMessage {
        text: String,
    },
    SetName {
        name: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::SeedDnd5EAction { .. } => "seed_dnd_5_e_action",
            Reducer::SeedDnd5EBackground { .. } => "seed_dnd_5_e_background",
            Reducer::SeedDnd5ECharCreationOption { .. } => "seed_dnd_5_e_char_creation_option",
            Reducer::SeedDnd5EClass { .. } => "seed_dnd_5_e_class",
            Reducer::SeedDnd5EClassFeature { .. } => "seed_dnd_5_e_class_feature",
            Reducer::SeedDnd5ECondition { .. } => "seed_dnd_5_e_condition",
            Reducer::SeedDnd5ECultBoon { .. } => "seed_dnd_5_e_cult_boon",
            Reducer::SeedDnd5EDeck { .. } => "seed_dnd_5_e_deck",
            Reducer::SeedDnd5EDeity { .. } => "seed_dnd_5_e_deity",
            Reducer::SeedDnd5EFeat { .. } => "seed_dnd_5_e_feat",
            Reducer::SeedDnd5EItem { .. } => "seed_dnd_5_e_item",
            Reducer::SeedDnd5ELanguage { .. } => "seed_dnd_5_e_language",
            Reducer::SeedDnd5EMonster { .. } => "seed_dnd_5_e_monster",
            Reducer::SeedDnd5EObject { .. } => "seed_dnd_5_e_object",
            Reducer::SeedDnd5EOptionalFeature { .. } => "seed_dnd_5_e_optional_feature",
            Reducer::SeedDnd5EPsionic { .. } => "seed_dnd_5_e_psionic",
            Reducer::SeedDnd5ERace { .. } => "seed_dnd_5_e_race",
            Reducer::SeedDnd5ERecipe { .. } => "seed_dnd_5_e_recipe",
            Reducer::SeedDnd5EReward { .. } => "seed_dnd_5_e_reward",
            Reducer::SeedDnd5ESense { .. } => "seed_dnd_5_e_sense",
            Reducer::SeedDnd5ESkill { .. } => "seed_dnd_5_e_skill",
            Reducer::SeedDnd5ESpell { .. } => "seed_dnd_5_e_spell",
            Reducer::SeedDnd5ESubclass { .. } => "seed_dnd_5_e_subclass",
            Reducer::SeedDnd5ESubclassFeature { .. } => "seed_dnd_5_e_subclass_feature",
            Reducer::SeedDnd5ETrapHazard { .. } => "seed_dnd_5_e_trap_hazard",
            Reducer::SeedDnd5EVariantRule { .. } => "seed_dnd_5_e_variant_rule",
            Reducer::SeedDnd5EVehicle { .. } => "seed_dnd_5_e_vehicle",
            Reducer::SendMessage { .. } => "send_message",
            Reducer::SetName { .. } => "set_name",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::SeedDnd5EAction {
                name,
                source,
                time,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_action_reducer::SeedDnd5EActionArgs {
                name: name.clone(),
                source: source.clone(),
                time: time.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EBackground {
                name,
                source,
                skill_proficiencies,
                tool_proficiencies,
                language_proficiencies,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_background_reducer::SeedDnd5EBackgroundArgs {
                name: name.clone(),
                source: source.clone(),
                skill_proficiencies: skill_proficiencies.clone(),
                tool_proficiencies: tool_proficiencies.clone(),
                language_proficiencies: language_proficiencies.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ECharCreationOption {
                name,
                source,
                option_types,
                description,
            } => __sats::bsatn::to_vec(
                &seed_dnd_5_e_char_creation_option_reducer::SeedDnd5ECharCreationOptionArgs {
                    name: name.clone(),
                    source: source.clone(),
                    option_types: option_types.clone(),
                    description: description.clone(),
                },
            ),
            Reducer::SeedDnd5EClass {
                name,
                source,
                edition,
                hit_die,
                saving_throws,
                spellcasting_ability,
                caster_progression,
                prepared_spells_formula,
                prepared_spells_progression,
                cantrip_progression,
                class_features,
                subclass_title,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_class_reducer::SeedDnd5EClassArgs {
                name: name.clone(),
                source: source.clone(),
                edition: edition.clone(),
                hit_die: hit_die.clone(),
                saving_throws: saving_throws.clone(),
                spellcasting_ability: spellcasting_ability.clone(),
                caster_progression: caster_progression.clone(),
                prepared_spells_formula: prepared_spells_formula.clone(),
                prepared_spells_progression: prepared_spells_progression.clone(),
                cantrip_progression: cantrip_progression.clone(),
                class_features: class_features.clone(),
                subclass_title: subclass_title.clone(),
            }),
            Reducer::SeedDnd5EClassFeature {
                name,
                source,
                class_name,
                class_source,
                level,
                description,
            } => __sats::bsatn::to_vec(
                &seed_dnd_5_e_class_feature_reducer::SeedDnd5EClassFeatureArgs {
                    name: name.clone(),
                    source: source.clone(),
                    class_name: class_name.clone(),
                    class_source: class_source.clone(),
                    level: level.clone(),
                    description: description.clone(),
                },
            ),
            Reducer::SeedDnd5ECondition {
                name,
                source,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_condition_reducer::SeedDnd5EConditionArgs {
                name: name.clone(),
                source: source.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ECultBoon {
                name,
                source,
                kind,
                subtype,
                goal,
                cultists,
                signature_spells,
                ability_text,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_cult_boon_reducer::SeedDnd5ECultBoonArgs {
                name: name.clone(),
                source: source.clone(),
                kind: kind.clone(),
                subtype: subtype.clone(),
                goal: goal.clone(),
                cultists: cultists.clone(),
                signature_spells: signature_spells.clone(),
                ability_text: ability_text.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EDeck {
                name,
                source,
                cards,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_deck_reducer::SeedDnd5EDeckArgs {
                name: name.clone(),
                source: source.clone(),
                cards: cards.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EDeity {
                name,
                source,
                pantheon,
                alignment,
                category,
                domains,
                province,
                title,
                symbol,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_deity_reducer::SeedDnd5EDeityArgs {
                name: name.clone(),
                source: source.clone(),
                pantheon: pantheon.clone(),
                alignment: alignment.clone(),
                category: category.clone(),
                domains: domains.clone(),
                province: province.clone(),
                title: title.clone(),
                symbol: symbol.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EFeat {
                name,
                source,
                category,
                prerequisite,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_feat_reducer::SeedDnd5EFeatArgs {
                name: name.clone(),
                source: source.clone(),
                category: category.clone(),
                prerequisite: prerequisite.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EItem {
                name,
                source,
                item_type,
                rarity,
                weight,
                value_cp,
                wondrous,
                attunement,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_item_reducer::SeedDnd5EItemArgs {
                name: name.clone(),
                source: source.clone(),
                item_type: item_type.clone(),
                rarity: rarity.clone(),
                weight: weight.clone(),
                value_cp: value_cp.clone(),
                wondrous: wondrous.clone(),
                attunement: attunement.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ELanguage {
                name,
                source,
                kind,
                script,
                origin,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_language_reducer::SeedDnd5ELanguageArgs {
                name: name.clone(),
                source: source.clone(),
                kind: kind.clone(),
                script: script.clone(),
                origin: origin.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EMonster {
                name,
                source,
                size,
                creature_type,
                cr,
                ac,
                hp_average,
                hp_formula,
                speed_walk,
                speed_fly,
                speed_swim,
                str_score,
                dex_score,
                con_score,
                int_score,
                wis_score,
                cha_score,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_monster_reducer::SeedDnd5EMonsterArgs {
                name: name.clone(),
                source: source.clone(),
                size: size.clone(),
                creature_type: creature_type.clone(),
                cr: cr.clone(),
                ac: ac.clone(),
                hp_average: hp_average.clone(),
                hp_formula: hp_formula.clone(),
                speed_walk: speed_walk.clone(),
                speed_fly: speed_fly.clone(),
                speed_swim: speed_swim.clone(),
                str_score: str_score.clone(),
                dex_score: dex_score.clone(),
                con_score: con_score.clone(),
                int_score: int_score.clone(),
                wis_score: wis_score.clone(),
                cha_score: cha_score.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5EObject {
                name,
                source,
                size,
                object_type,
                ac,
                hp,
                description,
                action_description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_object_reducer::SeedDnd5EObjectArgs {
                name: name.clone(),
                source: source.clone(),
                size: size.clone(),
                object_type: object_type.clone(),
                ac: ac.clone(),
                hp: hp.clone(),
                description: description.clone(),
                action_description: action_description.clone(),
            }),
            Reducer::SeedDnd5EOptionalFeature {
                name,
                source,
                feature_types,
                prerequisite,
                description,
            } => __sats::bsatn::to_vec(
                &seed_dnd_5_e_optional_feature_reducer::SeedDnd5EOptionalFeatureArgs {
                    name: name.clone(),
                    source: source.clone(),
                    feature_types: feature_types.clone(),
                    prerequisite: prerequisite.clone(),
                    description: description.clone(),
                },
            ),
            Reducer::SeedDnd5EPsionic {
                name,
                source,
                kind,
                order_name,
                focus,
                description,
                modes,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_psionic_reducer::SeedDnd5EPsionicArgs {
                name: name.clone(),
                source: source.clone(),
                kind: kind.clone(),
                order_name: order_name.clone(),
                focus: focus.clone(),
                description: description.clone(),
                modes: modes.clone(),
            }),
            Reducer::SeedDnd5ERace {
                name,
                source,
                size,
                speed,
                ability_bonuses,
                language_proficiencies,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_race_reducer::SeedDnd5ERaceArgs {
                name: name.clone(),
                source: source.clone(),
                size: size.clone(),
                speed: speed.clone(),
                ability_bonuses: ability_bonuses.clone(),
                language_proficiencies: language_proficiencies.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ERecipe {
                name,
                source,
                recipe_type,
                dish_types,
                diet,
                serves,
                ingredients,
                instructions,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_recipe_reducer::SeedDnd5ERecipeArgs {
                name: name.clone(),
                source: source.clone(),
                recipe_type: recipe_type.clone(),
                dish_types: dish_types.clone(),
                diet: diet.clone(),
                serves: serves.clone(),
                ingredients: ingredients.clone(),
                instructions: instructions.clone(),
            }),
            Reducer::SeedDnd5EReward {
                name,
                source,
                reward_type,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_reward_reducer::SeedDnd5ERewardArgs {
                name: name.clone(),
                source: source.clone(),
                reward_type: reward_type.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ESense {
                name,
                source,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_sense_reducer::SeedDnd5ESenseArgs {
                name: name.clone(),
                source: source.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ESkill {
                name,
                source,
                ability,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_skill_reducer::SeedDnd5ESkillArgs {
                name: name.clone(),
                source: source.clone(),
                ability: ability.clone(),
                description: description.clone(),
            }),
            Reducer::SeedDnd5ESpell {
                name,
                source,
                level,
                school,
                ritual,
                concentration,
                description,
                saving_throw,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_spell_reducer::SeedDnd5ESpellArgs {
                name: name.clone(),
                source: source.clone(),
                level: level.clone(),
                school: school.clone(),
                ritual: ritual.clone(),
                concentration: concentration.clone(),
                description: description.clone(),
                saving_throw: saving_throw.clone(),
            }),
            Reducer::SeedDnd5ESubclass {
                name,
                short_name,
                source,
                class_name,
                class_source,
                edition,
                spellcasting_ability,
                caster_progression,
                cantrip_progression,
                subclass_features,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_subclass_reducer::SeedDnd5ESubclassArgs {
                name: name.clone(),
                short_name: short_name.clone(),
                source: source.clone(),
                class_name: class_name.clone(),
                class_source: class_source.clone(),
                edition: edition.clone(),
                spellcasting_ability: spellcasting_ability.clone(),
                caster_progression: caster_progression.clone(),
                cantrip_progression: cantrip_progression.clone(),
                subclass_features: subclass_features.clone(),
            }),
            Reducer::SeedDnd5ESubclassFeature {
                name,
                source,
                class_name,
                class_source,
                subclass_short_name,
                subclass_source,
                level,
                description,
            } => __sats::bsatn::to_vec(
                &seed_dnd_5_e_subclass_feature_reducer::SeedDnd5ESubclassFeatureArgs {
                    name: name.clone(),
                    source: source.clone(),
                    class_name: class_name.clone(),
                    class_source: class_source.clone(),
                    subclass_short_name: subclass_short_name.clone(),
                    subclass_source: subclass_source.clone(),
                    level: level.clone(),
                    description: description.clone(),
                },
            ),
            Reducer::SeedDnd5ETrapHazard {
                name,
                source,
                kind,
                trap_hazard_type,
                trigger,
                effect,
                countermeasures,
                description,
            } => {
                __sats::bsatn::to_vec(&seed_dnd_5_e_trap_hazard_reducer::SeedDnd5ETrapHazardArgs {
                    name: name.clone(),
                    source: source.clone(),
                    kind: kind.clone(),
                    trap_hazard_type: trap_hazard_type.clone(),
                    trigger: trigger.clone(),
                    effect: effect.clone(),
                    countermeasures: countermeasures.clone(),
                    description: description.clone(),
                })
            }
            Reducer::SeedDnd5EVariantRule {
                name,
                source,
                rule_type,
                description,
            } => __sats::bsatn::to_vec(
                &seed_dnd_5_e_variant_rule_reducer::SeedDnd5EVariantRuleArgs {
                    name: name.clone(),
                    source: source.clone(),
                    rule_type: rule_type.clone(),
                    description: description.clone(),
                },
            ),
            Reducer::SeedDnd5EVehicle {
                name,
                source,
                vehicle_type,
                size,
                terrain,
                crew_capacity,
                passenger_capacity,
                pace,
                ac,
                hp,
                description,
            } => __sats::bsatn::to_vec(&seed_dnd_5_e_vehicle_reducer::SeedDnd5EVehicleArgs {
                name: name.clone(),
                source: source.clone(),
                vehicle_type: vehicle_type.clone(),
                size: size.clone(),
                terrain: terrain.clone(),
                crew_capacity: crew_capacity.clone(),
                passenger_capacity: passenger_capacity.clone(),
                pace: pace.clone(),
                ac: ac.clone(),
                hp: hp.clone(),
                description: description.clone(),
            }),
            Reducer::SendMessage { text } => {
                __sats::bsatn::to_vec(&send_message_reducer::SendMessageArgs { text: text.clone() })
            }
            Reducer::SetName { name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { name: name.clone() })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    dnd_5_e_action: __sdk::TableUpdate<Dnd5EAction>,
    dnd_5_e_background: __sdk::TableUpdate<Dnd5EBackground>,
    dnd_5_e_char_creation_option: __sdk::TableUpdate<Dnd5ECharCreationOption>,
    dnd_5_e_class: __sdk::TableUpdate<Dnd5EClass>,
    dnd_5_e_class_feature: __sdk::TableUpdate<Dnd5EClassFeature>,
    dnd_5_e_condition: __sdk::TableUpdate<Dnd5ECondition>,
    dnd_5_e_cult_boon: __sdk::TableUpdate<Dnd5ECultBoon>,
    dnd_5_e_deck: __sdk::TableUpdate<Dnd5EDeck>,
    dnd_5_e_deity: __sdk::TableUpdate<Dnd5EDeity>,
    dnd_5_e_feat: __sdk::TableUpdate<Dnd5EFeat>,
    dnd_5_e_item: __sdk::TableUpdate<Dnd5EItem>,
    dnd_5_e_language: __sdk::TableUpdate<Dnd5ELanguage>,
    dnd_5_e_monster: __sdk::TableUpdate<Dnd5EMonster>,
    dnd_5_e_object: __sdk::TableUpdate<Dnd5EObject>,
    dnd_5_e_optional_feature: __sdk::TableUpdate<Dnd5EOptionalFeature>,
    dnd_5_e_psionic: __sdk::TableUpdate<Dnd5EPsionic>,
    dnd_5_e_race: __sdk::TableUpdate<Dnd5ERace>,
    dnd_5_e_recipe: __sdk::TableUpdate<Dnd5ERecipe>,
    dnd_5_e_reward: __sdk::TableUpdate<Dnd5EReward>,
    dnd_5_e_sense: __sdk::TableUpdate<Dnd5ESense>,
    dnd_5_e_skill: __sdk::TableUpdate<Dnd5ESkill>,
    dnd_5_e_spell: __sdk::TableUpdate<Dnd5ESpell>,
    dnd_5_e_subclass: __sdk::TableUpdate<Dnd5ESubclass>,
    dnd_5_e_subclass_feature: __sdk::TableUpdate<Dnd5ESubclassFeature>,
    dnd_5_e_trap_hazard: __sdk::TableUpdate<Dnd5ETrapHazard>,
    dnd_5_e_variant_rule: __sdk::TableUpdate<Dnd5EVariantRule>,
    dnd_5_e_vehicle: __sdk::TableUpdate<Dnd5EVehicle>,
    message: __sdk::TableUpdate<Message>,
    user: __sdk::TableUpdate<User>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "dnd_5_e_action" => db_update
                    .dnd_5_e_action
                    .append(dnd_5_e_action_table::parse_table_update(table_update)?),
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(dnd_5_e_background_table::parse_table_update(table_update)?),
                "dnd_5_e_char_creation_option" => db_update.dnd_5_e_char_creation_option.append(
                    dnd_5_e_char_creation_option_table::parse_table_update(table_update)?,
                ),
                "dnd_5_e_class" => db_update
                    .dnd_5_e_class
                    .append(dnd_5_e_class_table::parse_table_update(table_update)?),
                "dnd_5_e_class_feature" => db_update.dnd_5_e_class_feature.append(
                    dnd_5_e_class_feature_table::parse_table_update(table_update)?,
                ),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(dnd_5_e_condition_table::parse_table_update(table_update)?),
                "dnd_5_e_cult_boon" => db_update
                    .dnd_5_e_cult_boon
                    .append(dnd_5_e_cult_boon_table::parse_table_update(table_update)?),
                "dnd_5_e_deck" => db_update
                    .dnd_5_e_deck
                    .append(dnd_5_e_deck_table::parse_table_update(table_update)?),
                "dnd_5_e_deity" => db_update
                    .dnd_5_e_deity
                    .append(dnd_5_e_deity_table::parse_table_update(table_update)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(dnd_5_e_feat_table::parse_table_update(table_update)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(dnd_5_e_item_table::parse_table_update(table_update)?),
                "dnd_5_e_language" => db_update
                    .dnd_5_e_language
                    .append(dnd_5_e_language_table::parse_table_update(table_update)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(dnd_5_e_monster_table::parse_table_update(table_update)?),
                "dnd_5_e_object" => db_update
                    .dnd_5_e_object
                    .append(dnd_5_e_object_table::parse_table_update(table_update)?),
                "dnd_5_e_optional_feature" => db_update.dnd_5_e_optional_feature.append(
                    dnd_5_e_optional_feature_table::parse_table_update(table_update)?,
                ),
                "dnd_5_e_psionic" => db_update
                    .dnd_5_e_psionic
                    .append(dnd_5_e_psionic_table::parse_table_update(table_update)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(dnd_5_e_race_table::parse_table_update(table_update)?),
                "dnd_5_e_recipe" => db_update
                    .dnd_5_e_recipe
                    .append(dnd_5_e_recipe_table::parse_table_update(table_update)?),
                "dnd_5_e_reward" => db_update
                    .dnd_5_e_reward
                    .append(dnd_5_e_reward_table::parse_table_update(table_update)?),
                "dnd_5_e_sense" => db_update
                    .dnd_5_e_sense
                    .append(dnd_5_e_sense_table::parse_table_update(table_update)?),
                "dnd_5_e_skill" => db_update
                    .dnd_5_e_skill
                    .append(dnd_5_e_skill_table::parse_table_update(table_update)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(dnd_5_e_spell_table::parse_table_update(table_update)?),
                "dnd_5_e_subclass" => db_update
                    .dnd_5_e_subclass
                    .append(dnd_5_e_subclass_table::parse_table_update(table_update)?),
                "dnd_5_e_subclass_feature" => db_update.dnd_5_e_subclass_feature.append(
                    dnd_5_e_subclass_feature_table::parse_table_update(table_update)?,
                ),
                "dnd_5_e_trap_hazard" => db_update
                    .dnd_5_e_trap_hazard
                    .append(dnd_5_e_trap_hazard_table::parse_table_update(table_update)?),
                "dnd_5_e_variant_rule" => db_update.dnd_5_e_variant_rule.append(
                    dnd_5_e_variant_rule_table::parse_table_update(table_update)?,
                ),
                "dnd_5_e_vehicle" => db_update
                    .dnd_5_e_vehicle
                    .append(dnd_5_e_vehicle_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.dnd_5_e_action = cache
            .apply_diff_to_table::<Dnd5EAction>("dnd_5_e_action", &self.dnd_5_e_action)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_background = cache
            .apply_diff_to_table::<Dnd5EBackground>("dnd_5_e_background", &self.dnd_5_e_background)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_char_creation_option = cache
            .apply_diff_to_table::<Dnd5ECharCreationOption>(
                "dnd_5_e_char_creation_option",
                &self.dnd_5_e_char_creation_option,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_class = cache
            .apply_diff_to_table::<Dnd5EClass>("dnd_5_e_class", &self.dnd_5_e_class)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_class_feature = cache
            .apply_diff_to_table::<Dnd5EClassFeature>(
                "dnd_5_e_class_feature",
                &self.dnd_5_e_class_feature,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_condition = cache
            .apply_diff_to_table::<Dnd5ECondition>("dnd_5_e_condition", &self.dnd_5_e_condition)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_cult_boon = cache
            .apply_diff_to_table::<Dnd5ECultBoon>("dnd_5_e_cult_boon", &self.dnd_5_e_cult_boon)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_deck = cache
            .apply_diff_to_table::<Dnd5EDeck>("dnd_5_e_deck", &self.dnd_5_e_deck)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_deity = cache
            .apply_diff_to_table::<Dnd5EDeity>("dnd_5_e_deity", &self.dnd_5_e_deity)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_feat = cache
            .apply_diff_to_table::<Dnd5EFeat>("dnd_5_e_feat", &self.dnd_5_e_feat)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_item = cache
            .apply_diff_to_table::<Dnd5EItem>("dnd_5_e_item", &self.dnd_5_e_item)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_language = cache
            .apply_diff_to_table::<Dnd5ELanguage>("dnd_5_e_language", &self.dnd_5_e_language)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_monster = cache
            .apply_diff_to_table::<Dnd5EMonster>("dnd_5_e_monster", &self.dnd_5_e_monster)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_object = cache
            .apply_diff_to_table::<Dnd5EObject>("dnd_5_e_object", &self.dnd_5_e_object)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_optional_feature = cache
            .apply_diff_to_table::<Dnd5EOptionalFeature>(
                "dnd_5_e_optional_feature",
                &self.dnd_5_e_optional_feature,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_psionic = cache
            .apply_diff_to_table::<Dnd5EPsionic>("dnd_5_e_psionic", &self.dnd_5_e_psionic)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_race = cache
            .apply_diff_to_table::<Dnd5ERace>("dnd_5_e_race", &self.dnd_5_e_race)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_recipe = cache
            .apply_diff_to_table::<Dnd5ERecipe>("dnd_5_e_recipe", &self.dnd_5_e_recipe)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_reward = cache
            .apply_diff_to_table::<Dnd5EReward>("dnd_5_e_reward", &self.dnd_5_e_reward)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_sense = cache
            .apply_diff_to_table::<Dnd5ESense>("dnd_5_e_sense", &self.dnd_5_e_sense)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_skill = cache
            .apply_diff_to_table::<Dnd5ESkill>("dnd_5_e_skill", &self.dnd_5_e_skill)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_spell = cache
            .apply_diff_to_table::<Dnd5ESpell>("dnd_5_e_spell", &self.dnd_5_e_spell)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_subclass = cache
            .apply_diff_to_table::<Dnd5ESubclass>("dnd_5_e_subclass", &self.dnd_5_e_subclass)
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_subclass_feature = cache
            .apply_diff_to_table::<Dnd5ESubclassFeature>(
                "dnd_5_e_subclass_feature",
                &self.dnd_5_e_subclass_feature,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_trap_hazard = cache
            .apply_diff_to_table::<Dnd5ETrapHazard>(
                "dnd_5_e_trap_hazard",
                &self.dnd_5_e_trap_hazard,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_variant_rule = cache
            .apply_diff_to_table::<Dnd5EVariantRule>(
                "dnd_5_e_variant_rule",
                &self.dnd_5_e_variant_rule,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.dnd_5_e_vehicle = cache
            .apply_diff_to_table::<Dnd5EVehicle>("dnd_5_e_vehicle", &self.dnd_5_e_vehicle)
            .with_updates_by_pk(|row| &row.id);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "dnd_5_e_action" => db_update
                    .dnd_5_e_action
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_char_creation_option" => db_update
                    .dnd_5_e_char_creation_option
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_class" => db_update
                    .dnd_5_e_class
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_class_feature" => db_update
                    .dnd_5_e_class_feature
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_cult_boon" => db_update
                    .dnd_5_e_cult_boon
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_deck" => db_update
                    .dnd_5_e_deck
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_deity" => db_update
                    .dnd_5_e_deity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_language" => db_update
                    .dnd_5_e_language
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_object" => db_update
                    .dnd_5_e_object
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_optional_feature" => db_update
                    .dnd_5_e_optional_feature
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_psionic" => db_update
                    .dnd_5_e_psionic
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_recipe" => db_update
                    .dnd_5_e_recipe
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_reward" => db_update
                    .dnd_5_e_reward
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_sense" => db_update
                    .dnd_5_e_sense
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_skill" => db_update
                    .dnd_5_e_skill
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_subclass" => db_update
                    .dnd_5_e_subclass
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_subclass_feature" => db_update
                    .dnd_5_e_subclass_feature
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_trap_hazard" => db_update
                    .dnd_5_e_trap_hazard
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_variant_rule" => db_update
                    .dnd_5_e_variant_rule
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "dnd_5_e_vehicle" => db_update
                    .dnd_5_e_vehicle
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "dnd_5_e_action" => db_update
                    .dnd_5_e_action
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_background" => db_update
                    .dnd_5_e_background
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_char_creation_option" => db_update
                    .dnd_5_e_char_creation_option
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_class" => db_update
                    .dnd_5_e_class
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_class_feature" => db_update
                    .dnd_5_e_class_feature
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_condition" => db_update
                    .dnd_5_e_condition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_cult_boon" => db_update
                    .dnd_5_e_cult_boon
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_deck" => db_update
                    .dnd_5_e_deck
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_deity" => db_update
                    .dnd_5_e_deity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_feat" => db_update
                    .dnd_5_e_feat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_item" => db_update
                    .dnd_5_e_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_language" => db_update
                    .dnd_5_e_language
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_monster" => db_update
                    .dnd_5_e_monster
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_object" => db_update
                    .dnd_5_e_object
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_optional_feature" => db_update
                    .dnd_5_e_optional_feature
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_psionic" => db_update
                    .dnd_5_e_psionic
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_race" => db_update
                    .dnd_5_e_race
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_recipe" => db_update
                    .dnd_5_e_recipe
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_reward" => db_update
                    .dnd_5_e_reward
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_sense" => db_update
                    .dnd_5_e_sense
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_skill" => db_update
                    .dnd_5_e_skill
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_spell" => db_update
                    .dnd_5_e_spell
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_subclass" => db_update
                    .dnd_5_e_subclass
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_subclass_feature" => db_update
                    .dnd_5_e_subclass_feature
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_trap_hazard" => db_update
                    .dnd_5_e_trap_hazard
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_variant_rule" => db_update
                    .dnd_5_e_variant_rule
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "dnd_5_e_vehicle" => db_update
                    .dnd_5_e_vehicle
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    dnd_5_e_action: __sdk::TableAppliedDiff<'r, Dnd5EAction>,
    dnd_5_e_background: __sdk::TableAppliedDiff<'r, Dnd5EBackground>,
    dnd_5_e_char_creation_option: __sdk::TableAppliedDiff<'r, Dnd5ECharCreationOption>,
    dnd_5_e_class: __sdk::TableAppliedDiff<'r, Dnd5EClass>,
    dnd_5_e_class_feature: __sdk::TableAppliedDiff<'r, Dnd5EClassFeature>,
    dnd_5_e_condition: __sdk::TableAppliedDiff<'r, Dnd5ECondition>,
    dnd_5_e_cult_boon: __sdk::TableAppliedDiff<'r, Dnd5ECultBoon>,
    dnd_5_e_deck: __sdk::TableAppliedDiff<'r, Dnd5EDeck>,
    dnd_5_e_deity: __sdk::TableAppliedDiff<'r, Dnd5EDeity>,
    dnd_5_e_feat: __sdk::TableAppliedDiff<'r, Dnd5EFeat>,
    dnd_5_e_item: __sdk::TableAppliedDiff<'r, Dnd5EItem>,
    dnd_5_e_language: __sdk::TableAppliedDiff<'r, Dnd5ELanguage>,
    dnd_5_e_monster: __sdk::TableAppliedDiff<'r, Dnd5EMonster>,
    dnd_5_e_object: __sdk::TableAppliedDiff<'r, Dnd5EObject>,
    dnd_5_e_optional_feature: __sdk::TableAppliedDiff<'r, Dnd5EOptionalFeature>,
    dnd_5_e_psionic: __sdk::TableAppliedDiff<'r, Dnd5EPsionic>,
    dnd_5_e_race: __sdk::TableAppliedDiff<'r, Dnd5ERace>,
    dnd_5_e_recipe: __sdk::TableAppliedDiff<'r, Dnd5ERecipe>,
    dnd_5_e_reward: __sdk::TableAppliedDiff<'r, Dnd5EReward>,
    dnd_5_e_sense: __sdk::TableAppliedDiff<'r, Dnd5ESense>,
    dnd_5_e_skill: __sdk::TableAppliedDiff<'r, Dnd5ESkill>,
    dnd_5_e_spell: __sdk::TableAppliedDiff<'r, Dnd5ESpell>,
    dnd_5_e_subclass: __sdk::TableAppliedDiff<'r, Dnd5ESubclass>,
    dnd_5_e_subclass_feature: __sdk::TableAppliedDiff<'r, Dnd5ESubclassFeature>,
    dnd_5_e_trap_hazard: __sdk::TableAppliedDiff<'r, Dnd5ETrapHazard>,
    dnd_5_e_variant_rule: __sdk::TableAppliedDiff<'r, Dnd5EVariantRule>,
    dnd_5_e_vehicle: __sdk::TableAppliedDiff<'r, Dnd5EVehicle>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    user: __sdk::TableAppliedDiff<'r, User>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Dnd5EAction>(
            "dnd_5_e_action",
            &self.dnd_5_e_action,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EBackground>(
            "dnd_5_e_background",
            &self.dnd_5_e_background,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ECharCreationOption>(
            "dnd_5_e_char_creation_option",
            &self.dnd_5_e_char_creation_option,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EClass>(
            "dnd_5_e_class",
            &self.dnd_5_e_class,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EClassFeature>(
            "dnd_5_e_class_feature",
            &self.dnd_5_e_class_feature,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ECondition>(
            "dnd_5_e_condition",
            &self.dnd_5_e_condition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ECultBoon>(
            "dnd_5_e_cult_boon",
            &self.dnd_5_e_cult_boon,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EDeck>(
            "dnd_5_e_deck",
            &self.dnd_5_e_deck,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EDeity>(
            "dnd_5_e_deity",
            &self.dnd_5_e_deity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EFeat>(
            "dnd_5_e_feat",
            &self.dnd_5_e_feat,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EItem>(
            "dnd_5_e_item",
            &self.dnd_5_e_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ELanguage>(
            "dnd_5_e_language",
            &self.dnd_5_e_language,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EMonster>(
            "dnd_5_e_monster",
            &self.dnd_5_e_monster,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EObject>(
            "dnd_5_e_object",
            &self.dnd_5_e_object,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EOptionalFeature>(
            "dnd_5_e_optional_feature",
            &self.dnd_5_e_optional_feature,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EPsionic>(
            "dnd_5_e_psionic",
            &self.dnd_5_e_psionic,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ERace>(
            "dnd_5_e_race",
            &self.dnd_5_e_race,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ERecipe>(
            "dnd_5_e_recipe",
            &self.dnd_5_e_recipe,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EReward>(
            "dnd_5_e_reward",
            &self.dnd_5_e_reward,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESense>(
            "dnd_5_e_sense",
            &self.dnd_5_e_sense,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESkill>(
            "dnd_5_e_skill",
            &self.dnd_5_e_skill,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESpell>(
            "dnd_5_e_spell",
            &self.dnd_5_e_spell,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESubclass>(
            "dnd_5_e_subclass",
            &self.dnd_5_e_subclass,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ESubclassFeature>(
            "dnd_5_e_subclass_feature",
            &self.dnd_5_e_subclass_feature,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5ETrapHazard>(
            "dnd_5_e_trap_hazard",
            &self.dnd_5_e_trap_hazard,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EVariantRule>(
            "dnd_5_e_variant_rule",
            &self.dnd_5_e_variant_rule,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Dnd5EVehicle>(
            "dnd_5_e_vehicle",
            &self.dnd_5_e_vehicle,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        dnd_5_e_action_table::register_table(client_cache);
        dnd_5_e_background_table::register_table(client_cache);
        dnd_5_e_char_creation_option_table::register_table(client_cache);
        dnd_5_e_class_table::register_table(client_cache);
        dnd_5_e_class_feature_table::register_table(client_cache);
        dnd_5_e_condition_table::register_table(client_cache);
        dnd_5_e_cult_boon_table::register_table(client_cache);
        dnd_5_e_deck_table::register_table(client_cache);
        dnd_5_e_deity_table::register_table(client_cache);
        dnd_5_e_feat_table::register_table(client_cache);
        dnd_5_e_item_table::register_table(client_cache);
        dnd_5_e_language_table::register_table(client_cache);
        dnd_5_e_monster_table::register_table(client_cache);
        dnd_5_e_object_table::register_table(client_cache);
        dnd_5_e_optional_feature_table::register_table(client_cache);
        dnd_5_e_psionic_table::register_table(client_cache);
        dnd_5_e_race_table::register_table(client_cache);
        dnd_5_e_recipe_table::register_table(client_cache);
        dnd_5_e_reward_table::register_table(client_cache);
        dnd_5_e_sense_table::register_table(client_cache);
        dnd_5_e_skill_table::register_table(client_cache);
        dnd_5_e_spell_table::register_table(client_cache);
        dnd_5_e_subclass_table::register_table(client_cache);
        dnd_5_e_subclass_feature_table::register_table(client_cache);
        dnd_5_e_trap_hazard_table::register_table(client_cache);
        dnd_5_e_variant_rule_table::register_table(client_cache);
        dnd_5_e_vehicle_table::register_table(client_cache);
        message_table::register_table(client_cache);
        user_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "dnd_5_e_action",
        "dnd_5_e_background",
        "dnd_5_e_char_creation_option",
        "dnd_5_e_class",
        "dnd_5_e_class_feature",
        "dnd_5_e_condition",
        "dnd_5_e_cult_boon",
        "dnd_5_e_deck",
        "dnd_5_e_deity",
        "dnd_5_e_feat",
        "dnd_5_e_item",
        "dnd_5_e_language",
        "dnd_5_e_monster",
        "dnd_5_e_object",
        "dnd_5_e_optional_feature",
        "dnd_5_e_psionic",
        "dnd_5_e_race",
        "dnd_5_e_recipe",
        "dnd_5_e_reward",
        "dnd_5_e_sense",
        "dnd_5_e_skill",
        "dnd_5_e_spell",
        "dnd_5_e_subclass",
        "dnd_5_e_subclass_feature",
        "dnd_5_e_trap_hazard",
        "dnd_5_e_variant_rule",
        "dnd_5_e_vehicle",
        "message",
        "user",
    ];
}
