// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::class_level_prereq_type::ClassLevelPrereq;
use super::pact_boon_type::PactBoon;
use super::warlock_patron_type::WarlockPatron;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OptionalFeaturePrereq {
    pub level: Option<ClassLevelPrereq>,
    pub pact: Option<PactBoon>,
    pub patron: Option<WarlockPatron>,
}

impl __sdk::InModule for OptionalFeaturePrereq {
    type Module = super::RemoteModule;
}
