// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Profile {
    pub identity: __sdk::Identity,
    pub display_name: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub last_seen_at: __sdk::Timestamp,
}

impl __sdk::InModule for Profile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Profile`.
///
/// Provides typed access to columns for query building.
pub struct ProfileCols {
    pub identity: __sdk::__query_builder::Col<Profile, __sdk::Identity>,
    pub display_name: __sdk::__query_builder::Col<Profile, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Profile, __sdk::Timestamp>,
    pub last_seen_at: __sdk::__query_builder::Col<Profile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Profile {
    type Cols = ProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Profile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProfileIxCols {
    pub identity: __sdk::__query_builder::IxCol<Profile, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Profile {
    type IxCols = ProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProfileIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Profile {}
