// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum Race {
    Dragonborn,

    Dwarf,

    Elf,

    Gnome,

    HalfElf,

    Halfling,

    HalfOrc,

    Human,

    Tiefling,

    Aasimar,

    Firbolg,

    Goliath,

    Kenku,

    Lizardfolk,

    Tabaxi,

    Triton,

    Goblin,

    Hobgoblin,

    Bugbear,

    Orc,

    Kobold,

    Genasi,

    Tortle,

    Changeling,

    Shifter,

    Warforged,

    Kalashtar,

    Vampire,
}

impl __sdk::InModule for Race {
    type Module = super::RemoteModule;
}
