// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_type::Ability;
use super::caster_progression_type::CasterProgression;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ESubclassArgs {
    pub name: String,
    pub short_name: String,
    pub source: String,
    pub class_name: String,
    pub class_source: String,
    pub edition: Option<String>,
    pub spellcasting_ability: Option<Ability>,
    pub caster_progression: Option<CasterProgression>,
    pub cantrip_progression: Vec<u8>,
    pub subclass_features: Vec<String>,
}

impl From<SeedDnd5ESubclassArgs> for super::Reducer {
    fn from(args: SeedDnd5ESubclassArgs) -> Self {
        Self::SeedDnd5ESubclass {
            name: args.name,
            short_name: args.short_name,
            source: args.source,
            class_name: args.class_name,
            class_source: args.class_source,
            edition: args.edition,
            spellcasting_ability: args.spellcasting_ability,
            caster_progression: args.caster_progression,
            cantrip_progression: args.cantrip_progression,
            subclass_features: args.subclass_features,
        }
    }
}

impl __sdk::InModule for SeedDnd5ESubclassArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_subclass`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_subclass {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_subclass` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_subclass:seed_dnd_5_e_subclass_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_subclass(
        &self,
        name: String,
        short_name: String,
        source: String,
        class_name: String,
        class_source: String,
        edition: Option<String>,
        spellcasting_ability: Option<Ability>,
        caster_progression: Option<CasterProgression>,
        cantrip_progression: Vec<u8>,
        subclass_features: Vec<String>,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_subclass_then(
            name,
            short_name,
            source,
            class_name,
            class_source,
            edition,
            spellcasting_ability,
            caster_progression,
            cantrip_progression,
            subclass_features,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_subclass` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_subclass_then(
        &self,
        name: String,
        short_name: String,
        source: String,
        class_name: String,
        class_source: String,
        edition: Option<String>,
        spellcasting_ability: Option<Ability>,
        caster_progression: Option<CasterProgression>,
        cantrip_progression: Vec<u8>,
        subclass_features: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_subclass for super::RemoteReducers {
    fn seed_dnd_5_e_subclass_then(
        &self,
        name: String,
        short_name: String,
        source: String,
        class_name: String,
        class_source: String,
        edition: Option<String>,
        spellcasting_ability: Option<Ability>,
        caster_progression: Option<CasterProgression>,
        cantrip_progression: Vec<u8>,
        subclass_features: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ESubclassArgs {
                name,
                short_name,
                source,
                class_name,
                class_source,
                edition,
                spellcasting_ability,
                caster_progression,
                cantrip_progression,
                subclass_features,
            },
            callback,
        )
    }
}
