// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EDeckArgs {
    pub name: String,
    pub source: String,
    pub cards: Vec<String>,
    pub description: String,
}

impl From<SeedDnd5EDeckArgs> for super::Reducer {
    fn from(args: SeedDnd5EDeckArgs) -> Self {
        Self::SeedDnd5EDeck {
            name: args.name,
            source: args.source,
            cards: args.cards,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EDeckArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_deck`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_deck {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_deck` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_deck:seed_dnd_5_e_deck_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_deck(
        &self,
        name: String,
        source: String,
        cards: Vec<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_deck_then(name, source, cards, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_deck` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_deck_then(
        &self,
        name: String,
        source: String,
        cards: Vec<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_deck for super::RemoteReducers {
    fn seed_dnd_5_e_deck_then(
        &self,
        name: String,
        source: String,
        cards: Vec<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EDeckArgs {
                name,
                source,
                cards,
                description,
            },
            callback,
        )
    }
}
