// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::alignment_type::Alignment;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EDeityArgs {
    pub name: String,
    pub source: String,
    pub pantheon: Option<String>,
    pub alignment: Vec<Alignment>,
    pub category: Option<String>,
    pub domains: Vec<String>,
    pub province: Option<String>,
    pub title: Option<String>,
    pub symbol: Option<String>,
    pub description: String,
}

impl From<SeedDnd5EDeityArgs> for super::Reducer {
    fn from(args: SeedDnd5EDeityArgs) -> Self {
        Self::SeedDnd5EDeity {
            name: args.name,
            source: args.source,
            pantheon: args.pantheon,
            alignment: args.alignment,
            category: args.category,
            domains: args.domains,
            province: args.province,
            title: args.title,
            symbol: args.symbol,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EDeityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_deity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_deity {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_deity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_deity:seed_dnd_5_e_deity_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_deity(
        &self,
        name: String,
        source: String,
        pantheon: Option<String>,
        alignment: Vec<Alignment>,
        category: Option<String>,
        domains: Vec<String>,
        province: Option<String>,
        title: Option<String>,
        symbol: Option<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_deity_then(
            name,
            source,
            pantheon,
            alignment,
            category,
            domains,
            province,
            title,
            symbol,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_deity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_deity_then(
        &self,
        name: String,
        source: String,
        pantheon: Option<String>,
        alignment: Vec<Alignment>,
        category: Option<String>,
        domains: Vec<String>,
        province: Option<String>,
        title: Option<String>,
        symbol: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_deity for super::RemoteReducers {
    fn seed_dnd_5_e_deity_then(
        &self,
        name: String,
        source: String,
        pantheon: Option<String>,
        alignment: Vec<Alignment>,
        category: Option<String>,
        domains: Vec<String>,
        province: Option<String>,
        title: Option<String>,
        symbol: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EDeityArgs {
                name,
                source,
                pantheon,
                alignment,
                category,
                domains,
                province,
                title,
                symbol,
                description,
            },
            callback,
        )
    }
}
