// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EVehicleArgs {
    pub name: String,
    pub source: String,
    pub vehicle_type: String,
    pub size: Vec<String>,
    pub terrain: Vec<String>,
    pub crew_capacity: Option<u16>,
    pub passenger_capacity: Option<u16>,
    pub pace: Option<u16>,
    pub ac: Option<u16>,
    pub hp: Option<u16>,
    pub description: String,
}

impl From<SeedDnd5EVehicleArgs> for super::Reducer {
    fn from(args: SeedDnd5EVehicleArgs) -> Self {
        Self::SeedDnd5EVehicle {
            name: args.name,
            source: args.source,
            vehicle_type: args.vehicle_type,
            size: args.size,
            terrain: args.terrain,
            crew_capacity: args.crew_capacity,
            passenger_capacity: args.passenger_capacity,
            pace: args.pace,
            ac: args.ac,
            hp: args.hp,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EVehicleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_vehicle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_vehicle {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_vehicle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_vehicle:seed_dnd_5_e_vehicle_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_vehicle(
        &self,
        name: String,
        source: String,
        vehicle_type: String,
        size: Vec<String>,
        terrain: Vec<String>,
        crew_capacity: Option<u16>,
        passenger_capacity: Option<u16>,
        pace: Option<u16>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_vehicle_then(
            name,
            source,
            vehicle_type,
            size,
            terrain,
            crew_capacity,
            passenger_capacity,
            pace,
            ac,
            hp,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_vehicle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_vehicle_then(
        &self,
        name: String,
        source: String,
        vehicle_type: String,
        size: Vec<String>,
        terrain: Vec<String>,
        crew_capacity: Option<u16>,
        passenger_capacity: Option<u16>,
        pace: Option<u16>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_vehicle for super::RemoteReducers {
    fn seed_dnd_5_e_vehicle_then(
        &self,
        name: String,
        source: String,
        vehicle_type: String,
        size: Vec<String>,
        terrain: Vec<String>,
        crew_capacity: Option<u16>,
        passenger_capacity: Option<u16>,
        pace: Option<u16>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EVehicleArgs {
                name,
                source,
                vehicle_type,
                size,
                terrain,
                crew_capacity,
                passenger_capacity,
                pace,
                ac,
                hp,
                description,
            },
            callback,
        )
    }
}
