// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EVariantRuleArgs {
    pub name: String,
    pub source: String,
    pub rule_type: Option<String>,
    pub description: String,
}

impl From<SeedDnd5EVariantRuleArgs> for super::Reducer {
    fn from(args: SeedDnd5EVariantRuleArgs) -> Self {
        Self::SeedDnd5EVariantRule {
            name: args.name,
            source: args.source,
            rule_type: args.rule_type,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EVariantRuleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_variant_rule`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_variant_rule {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_variant_rule` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_variant_rule:seed_dnd_5_e_variant_rule_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_variant_rule(
        &self,
        name: String,
        source: String,
        rule_type: Option<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_variant_rule_then(name, source, rule_type, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_variant_rule` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_variant_rule_then(
        &self,
        name: String,
        source: String,
        rule_type: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_variant_rule for super::RemoteReducers {
    fn seed_dnd_5_e_variant_rule_then(
        &self,
        name: String,
        source: String,
        rule_type: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EVariantRuleArgs {
                name,
                source,
                rule_type,
                description,
            },
            callback,
        )
    }
}
