// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::feat_category_type::FeatCategory;
use super::feat_prereq_type::FeatPrereq;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EFeatArgs {
    pub name: String,
    pub source: String,
    pub category: Option<FeatCategory>,
    pub prerequisite: Option<FeatPrereq>,
    pub description: String,
}

impl From<SeedDnd5EFeatArgs> for super::Reducer {
    fn from(args: SeedDnd5EFeatArgs) -> Self {
        Self::SeedDnd5EFeat {
            name: args.name,
            source: args.source,
            category: args.category,
            prerequisite: args.prerequisite,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EFeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_feat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_feat {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_feat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_feat:seed_dnd_5_e_feat_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_feat(
        &self,
        name: String,
        source: String,
        category: Option<FeatCategory>,
        prerequisite: Option<FeatPrereq>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_feat_then(name, source, category, prerequisite, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_feat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_feat_then(
        &self,
        name: String,
        source: String,
        category: Option<FeatCategory>,
        prerequisite: Option<FeatPrereq>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_feat for super::RemoteReducers {
    fn seed_dnd_5_e_feat_then(
        &self,
        name: String,
        source: String,
        category: Option<FeatCategory>,
        prerequisite: Option<FeatPrereq>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EFeatArgs {
                name,
                source,
                category,
                prerequisite,
                description,
            },
            callback,
        )
    }
}
