// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ERewardArgs {
    pub name: String,
    pub source: String,
    pub reward_type: Option<String>,
    pub description: String,
}

impl From<SeedDnd5ERewardArgs> for super::Reducer {
    fn from(args: SeedDnd5ERewardArgs) -> Self {
        Self::SeedDnd5EReward {
            name: args.name,
            source: args.source,
            reward_type: args.reward_type,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5ERewardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_reward`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_reward {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_reward` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_reward:seed_dnd_5_e_reward_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_reward(
        &self,
        name: String,
        source: String,
        reward_type: Option<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_reward_then(name, source, reward_type, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_reward` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_reward_then(
        &self,
        name: String,
        source: String,
        reward_type: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_reward for super::RemoteReducers {
    fn seed_dnd_5_e_reward_then(
        &self,
        name: String,
        source: String,
        reward_type: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ERewardArgs {
                name,
                source,
                reward_type,
                description,
            },
            callback,
        )
    }
}
