// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::creature_size_type::CreatureSize;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EObjectArgs {
    pub name: String,
    pub source: String,
    pub size: Vec<CreatureSize>,
    pub object_type: Option<String>,
    pub ac: Option<u16>,
    pub hp: Option<u16>,
    pub description: String,
    pub action_description: String,
}

impl From<SeedDnd5EObjectArgs> for super::Reducer {
    fn from(args: SeedDnd5EObjectArgs) -> Self {
        Self::SeedDnd5EObject {
            name: args.name,
            source: args.source,
            size: args.size,
            object_type: args.object_type,
            ac: args.ac,
            hp: args.hp,
            description: args.description,
            action_description: args.action_description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EObjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_object {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_object:seed_dnd_5_e_object_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_object(
        &self,
        name: String,
        source: String,
        size: Vec<CreatureSize>,
        object_type: Option<String>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
        action_description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_object_then(
            name,
            source,
            size,
            object_type,
            ac,
            hp,
            description,
            action_description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_object` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_object_then(
        &self,
        name: String,
        source: String,
        size: Vec<CreatureSize>,
        object_type: Option<String>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
        action_description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_object for super::RemoteReducers {
    fn seed_dnd_5_e_object_then(
        &self,
        name: String,
        source: String,
        size: Vec<CreatureSize>,
        object_type: Option<String>,
        ac: Option<u16>,
        hp: Option<u16>,
        description: String,
        action_description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EObjectArgs {
                name,
                source,
                size,
                object_type,
                ac,
                hp,
                description,
                action_description,
            },
            callback,
        )
    }
}
