// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ERecipeArgs {
    pub name: String,
    pub source: String,
    pub recipe_type: Option<String>,
    pub dish_types: Vec<String>,
    pub diet: Option<String>,
    pub serves: Option<String>,
    pub ingredients: String,
    pub instructions: String,
}

impl From<SeedDnd5ERecipeArgs> for super::Reducer {
    fn from(args: SeedDnd5ERecipeArgs) -> Self {
        Self::SeedDnd5ERecipe {
            name: args.name,
            source: args.source,
            recipe_type: args.recipe_type,
            dish_types: args.dish_types,
            diet: args.diet,
            serves: args.serves,
            ingredients: args.ingredients,
            instructions: args.instructions,
        }
    }
}

impl __sdk::InModule for SeedDnd5ERecipeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_recipe`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_recipe {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_recipe` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_recipe:seed_dnd_5_e_recipe_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_recipe(
        &self,
        name: String,
        source: String,
        recipe_type: Option<String>,
        dish_types: Vec<String>,
        diet: Option<String>,
        serves: Option<String>,
        ingredients: String,
        instructions: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_recipe_then(
            name,
            source,
            recipe_type,
            dish_types,
            diet,
            serves,
            ingredients,
            instructions,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_recipe` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_recipe_then(
        &self,
        name: String,
        source: String,
        recipe_type: Option<String>,
        dish_types: Vec<String>,
        diet: Option<String>,
        serves: Option<String>,
        ingredients: String,
        instructions: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_recipe for super::RemoteReducers {
    fn seed_dnd_5_e_recipe_then(
        &self,
        name: String,
        source: String,
        recipe_type: Option<String>,
        dish_types: Vec<String>,
        diet: Option<String>,
        serves: Option<String>,
        ingredients: String,
        instructions: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ERecipeArgs {
                name,
                source,
                recipe_type,
                dish_types,
                diet,
                serves,
                ingredients,
                instructions,
            },
            callback,
        )
    }
}
