// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_rarity_type::ItemRarity;
use super::item_type_type::ItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5EItemArgs {
    pub name: String,
    pub source: String,
    pub item_type: ItemType,
    pub rarity: ItemRarity,
    pub weight: Option<f32>,
    pub value_cp: Option<u32>,
    pub wondrous: bool,
    pub attunement: Option<String>,
    pub description: String,
}

impl From<SeedDnd5EItemArgs> for super::Reducer {
    fn from(args: SeedDnd5EItemArgs) -> Self {
        Self::SeedDnd5EItem {
            name: args.name,
            source: args.source,
            item_type: args.item_type,
            rarity: args.rarity,
            weight: args.weight,
            value_cp: args.value_cp,
            wondrous: args.wondrous,
            attunement: args.attunement,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5EItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_item {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_item:seed_dnd_5_e_item_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_item(
        &self,
        name: String,
        source: String,
        item_type: ItemType,
        rarity: ItemRarity,
        weight: Option<f32>,
        value_cp: Option<u32>,
        wondrous: bool,
        attunement: Option<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_item_then(
            name,
            source,
            item_type,
            rarity,
            weight,
            value_cp,
            wondrous,
            attunement,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_item_then(
        &self,
        name: String,
        source: String,
        item_type: ItemType,
        rarity: ItemRarity,
        weight: Option<f32>,
        value_cp: Option<u32>,
        wondrous: bool,
        attunement: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_item for super::RemoteReducers {
    fn seed_dnd_5_e_item_then(
        &self,
        name: String,
        source: String,
        item_type: ItemType,
        rarity: ItemRarity,
        weight: Option<f32>,
        value_cp: Option<u32>,
        wondrous: bool,
        attunement: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5EItemArgs {
                name,
                source,
                item_type,
                rarity,
                weight,
                value_cp,
                wondrous,
                attunement,
                description,
            },
            callback,
        )
    }
}
