// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ECultBoonArgs {
    pub name: String,
    pub source: String,
    pub kind: String,
    pub subtype: Option<String>,
    pub goal: Option<String>,
    pub cultists: Option<String>,
    pub signature_spells: Option<String>,
    pub ability_text: Option<String>,
    pub description: String,
}

impl From<SeedDnd5ECultBoonArgs> for super::Reducer {
    fn from(args: SeedDnd5ECultBoonArgs) -> Self {
        Self::SeedDnd5ECultBoon {
            name: args.name,
            source: args.source,
            kind: args.kind,
            subtype: args.subtype,
            goal: args.goal,
            cultists: args.cultists,
            signature_spells: args.signature_spells,
            ability_text: args.ability_text,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5ECultBoonArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_cult_boon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_cult_boon {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_cult_boon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_cult_boon:seed_dnd_5_e_cult_boon_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_cult_boon(
        &self,
        name: String,
        source: String,
        kind: String,
        subtype: Option<String>,
        goal: Option<String>,
        cultists: Option<String>,
        signature_spells: Option<String>,
        ability_text: Option<String>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_cult_boon_then(
            name,
            source,
            kind,
            subtype,
            goal,
            cultists,
            signature_spells,
            ability_text,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_cult_boon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_cult_boon_then(
        &self,
        name: String,
        source: String,
        kind: String,
        subtype: Option<String>,
        goal: Option<String>,
        cultists: Option<String>,
        signature_spells: Option<String>,
        ability_text: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_cult_boon for super::RemoteReducers {
    fn seed_dnd_5_e_cult_boon_then(
        &self,
        name: String,
        source: String,
        kind: String,
        subtype: Option<String>,
        goal: Option<String>,
        cultists: Option<String>,
        signature_spells: Option<String>,
        ability_text: Option<String>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ECultBoonArgs {
                name,
                source,
                kind,
                subtype,
                goal,
                cultists,
                signature_spells,
                ability_text,
                description,
            },
            callback,
        )
    }
}
