// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_grant_type::AbilityGrant;
use super::creature_size_type::CreatureSize;
use super::language_grant_type::LanguageGrant;
use super::speed_type::Speed;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedDnd5ERaceArgs {
    pub name: String,
    pub source: String,
    pub size: CreatureSize,
    pub speed: Speed,
    pub ability_bonuses: Vec<AbilityGrant>,
    pub language_proficiencies: Vec<LanguageGrant>,
    pub description: String,
}

impl From<SeedDnd5ERaceArgs> for super::Reducer {
    fn from(args: SeedDnd5ERaceArgs) -> Self {
        Self::SeedDnd5ERace {
            name: args.name,
            source: args.source,
            size: args.size,
            speed: args.speed,
            ability_bonuses: args.ability_bonuses,
            language_proficiencies: args.language_proficiencies,
            description: args.description,
        }
    }
}

impl __sdk::InModule for SeedDnd5ERaceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_dnd_5_e_race`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_dnd_5_e_race {
    /// Request that the remote module invoke the reducer `seed_dnd_5_e_race` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_dnd_5_e_race:seed_dnd_5_e_race_then`] to run a callback after the reducer completes.
    fn seed_dnd_5_e_race(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        speed: Speed,
        ability_bonuses: Vec<AbilityGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,
    ) -> __sdk::Result<()> {
        self.seed_dnd_5_e_race_then(
            name,
            source,
            size,
            speed,
            ability_bonuses,
            language_proficiencies,
            description,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_dnd_5_e_race` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_dnd_5_e_race_then(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        speed: Speed,
        ability_bonuses: Vec<AbilityGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_dnd_5_e_race for super::RemoteReducers {
    fn seed_dnd_5_e_race_then(
        &self,
        name: String,
        source: String,
        size: CreatureSize,
        speed: Speed,
        ability_bonuses: Vec<AbilityGrant>,
        language_proficiencies: Vec<LanguageGrant>,
        description: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedDnd5ERaceArgs {
                name,
                source,
                size,
                speed,
                ability_bonuses,
                language_proficiencies,
                description,
            },
            callback,
        )
    }
}
